/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s2[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[7] = {0, 1, 2, 6, 7, 8, 9};
static const casadi_int casadi_s5[7] = {0, 1, 2, 9, 10, 11, 12};
static const casadi_int casadi_s6[7] = {0, 3, 6, 9, 13, 17, 21};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s8[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s9[7] = {3, 4, 5, 13, 14, 15, 16};
static const casadi_int casadi_s10[7] = {1, 4, 7, 10, 14, 18, 22};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s12[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s13[7] = {6, 7, 8, 17, 18, 19, 20};
static const casadi_int casadi_s14[7] = {2, 5, 8, 11, 15, 19, 23};
static const casadi_int casadi_s15[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s16[41] = 
  {13, 13, 0, 3, 6, 9, 9, 9,
  9, 13, 17, 21, 25, 25, 25, 25,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 6, 7, 8, 9, 6, 7, 8,
  9, 6, 7, 8, 9, 6, 7, 8,
  9};
static const casadi_int casadi_s17[3] = {13, 1, 1};
static const casadi_int casadi_s18[3] = {0, 1, 1};
static const casadi_int casadi_s19[3] = {17, 1, 1};
static const casadi_int casadi_s20[3] = {1, 1, 1};
static const casadi_int casadi_s21[3] = {0, 0, 1};
static const casadi_int casadi_s22[3] = {0, 13, 1};

/* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[0],i2[0],i3[17])->(o0,o1[13],o2[13x13,25nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55;
  casadi_real *w23=w+58, *w24=w+67, *w25=w+76, *w26=w+79, *w27=w+83, *w28=w+87, *w29=w+91, *w30=w+95, *w31=w+98, *w32=w+101, *w33=w+104, *w34=w+107;
  casadi_real *w35=w+116, *w36=w+119, *w37=w+123, *w38=w+126, *w39=w+129, w40, w41, w42, w43, w44, w45, *w46=w+139;
  casadi_real *w47=w+152, w48, w49, w50, w51, w52, w53, *w54=w+167, *w55=w+192, *w57=w+200, *w58=w+204, *w59=w+208;
  casadi_real *w60=w+212, *w61=w+215, *w62=w+218, w63, w64, *w65=w+223, w66, w67, w68, w69, w70, w71;
  casadi_real w72, *w73=w+234, *w74=w+241, *w75=w+243, *w76=w+246;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 25 */
  w02 = 25.;
  /* #40: @24 = @23; (@24[0] = @2) */
  casadi_copy(w23, 9, w24);
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #41: (@24[4] = @2) */
  for (rr=w24+4, cs=(&w02); rr!=w24+5; rr+=1) *rr = *cs++;
  /* #42: @2 = 30 */
  w02 = 30.;
  /* #43: (@24[8] = @2) */
  for (rr=w24+8, cs=(&w02); rr!=w24+9; rr+=1) *rr = *cs++;
  /* #44: @25 = mac(@22,@24,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #45: @2 = mac(@25,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #46: @9 = (-@9) */
  w09 = (- w09 );
  /* #47: @10 = (-@10) */
  w10 = (- w10 );
  /* #48: @11 = (-@11) */
  w11 = (- w11 );
  /* #49: @26 = vertcat(@8, @9, @10, @11) */
  rr=w26;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #50: @27 = @21[6:10] */
  for (rr=w27, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #51: @8 = ||@27||_F */
  w08 = casadi_norm_2(4, w27);
  /* #52: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #53: {@9, @10, @11, @3} = vertsplit(@26) */
  w09 = w26[0];
  w10 = w26[1];
  w11 = w26[2];
  w03 = w26[3];
  /* #54: @28 = @19[6:10] */
  for (rr=w28, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #55: {@4, @5, @6, @7} = vertsplit(@28) */
  w04 = w28[0];
  w05 = w28[1];
  w06 = w28[2];
  w07 = w28[3];
  /* #56: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #57: @13 = (@10*@5) */
  w13  = (w10*w05);
  /* #58: @12 = (@12-@13) */
  w12 -= w13;
  /* #59: @13 = (@11*@6) */
  w13  = (w11*w06);
  /* #60: @12 = (@12-@13) */
  w12 -= w13;
  /* #61: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #62: @12 = (@12-@13) */
  w12 -= w13;
  /* #63: @13 = (@12<@0) */
  w13  = (w12<w00);
  /* #64: @14 = (@9*@5) */
  w14  = (w09*w05);
  /* #65: @15 = (@10*@4) */
  w15  = (w10*w04);
  /* #66: @14 = (@14+@15) */
  w14 += w15;
  /* #67: @15 = (@11*@7) */
  w15  = (w11*w07);
  /* #68: @14 = (@14+@15) */
  w14 += w15;
  /* #69: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #70: @14 = (@14-@15) */
  w14 -= w15;
  /* #71: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #72: @16 = (@10*@7) */
  w16  = (w10*w07);
  /* #73: @15 = (@15-@16) */
  w15 -= w16;
  /* #74: @16 = (@11*@4) */
  w16  = (w11*w04);
  /* #75: @15 = (@15+@16) */
  w15 += w16;
  /* #76: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #77: @15 = (@15+@16) */
  w15 += w16;
  /* #78: @9 = (@9*@7) */
  w09 *= w07;
  /* #79: @10 = (@10*@6) */
  w10 *= w06;
  /* #80: @9 = (@9+@10) */
  w09 += w10;
  /* #81: @11 = (@11*@5) */
  w11 *= w05;
  /* #82: @9 = (@9-@11) */
  w09 -= w11;
  /* #83: @3 = (@3*@4) */
  w03 *= w04;
  /* #84: @9 = (@9+@3) */
  w09 += w03;
  /* #85: @28 = vertcat(@12, @14, @15, @9) */
  rr=w28;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  /* #86: @29 = (-@28) */
  for (i=0, rr=w29, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #87: @29 = (@13?@29:0) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #88: @12 = (!@13) */
  w12 = (! w13 );
  /* #89: @28 = (@12?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #90: @29 = (@29+@28) */
  for (i=0, rr=w29, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #91: @20 = @29[1:4] */
  for (rr=w20, cs=w29+1; cs!=w29+4; cs+=1) *rr++ = *cs;
  /* #92: @30 = (2.*@20) */
  for (i=0, rr=w30, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #93: @14 = ||@20||_F */
  w14 = casadi_norm_2(3, w20);
  /* #94: @15 = @29[0] */
  for (rr=(&w15), cs=w29+0; cs!=w29+1; cs+=1) *rr++ = *cs;
  /* #95: @9 = atan2(@14,@15) */
  w09  = atan2(w14,w15);
  /* #96: @31 = (@30*@9) */
  for (i=0, rr=w31, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w09);
  /* #97: @3 = 1e-09 */
  w03 = 1.0000000000000001e-09;
  /* #98: @3 = (@3+@14) */
  w03 += w14;
  /* #99: @31 = (@31/@3) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w03;
  /* #100: @32 = @31' */
  casadi_copy(w31, 3, w32);
  /* #101: @11 = 12 */
  w11 = 12.;
  /* #102: (@23[0] = @11) */
  for (rr=w23+0, cs=(&w11); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #103: (@23[4] = @11) */
  for (rr=w23+4, cs=(&w11); rr!=w23+5; rr+=1) *rr = *cs++;
  /* #104: (@23[8] = @11) */
  for (rr=w23+8, cs=(&w11); rr!=w23+9; rr+=1) *rr = *cs++;
  /* #105: @33 = mac(@32,@23,@1) */
  casadi_copy(w01, 3, w33);
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w32+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #106: @0 = mac(@33,@31,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #107: @2 = (@2+@0) */
  w02 += w00;
  /* #108: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #109: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #110: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #111: @29 = (-@26) */
  for (i=0, rr=w29, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #112: @28 = zeros(4x1) */
  casadi_clear(w28, 4);
  /* #113: @2 = sq(@14) */
  w02 = casadi_sq( w14 );
  /* #114: @0 = sq(@15) */
  w00 = casadi_sq( w15 );
  /* #115: @2 = (@2+@0) */
  w02 += w00;
  /* #116: @0 = (@14/@2) */
  w00  = (w14/w02);
  /* #117: @33 = @33' */
  /* #118: @34 = @23' */
  for (i=0, rr=w34, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #119: @35 = mac(@32,@34,@1) */
  casadi_copy(w01, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w32+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #120: @35 = @35' */
  /* #121: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #122: @35 = (@33/@3) */
  for (i=0, rr=w35, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #123: @11 = dot(@30, @35) */
  w11 = casadi_dot(3, w30, w35);
  /* #124: @10 = (@0*@11) */
  w10  = (w00*w11);
  /* #125: @10 = (-@10) */
  w10 = (- w10 );
  /* #126: @36 = @28; (@36[0] += @10) */
  casadi_copy(w28, 4, w36);
  for (rr=w36+0, cs=(&w10); rr!=w36+1; rr+=1) *rr += *cs++;
  /* #127: @31 = (@31/@3) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w03;
  /* #128: @32 = (-@31) */
  for (i=0, rr=w32, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #129: @10 = dot(@32, @33) */
  w10 = casadi_dot(3, w32, w33);
  /* #130: @16 = (@15/@2) */
  w16  = (w15/w02);
  /* #131: @17 = (@16*@11) */
  w17  = (w16*w11);
  /* #132: @10 = (@10+@17) */
  w10 += w17;
  /* #133: @10 = (@10/@14) */
  w10 /= w14;
  /* #134: @37 = (@10*@20) */
  for (i=0, rr=w37, cs=w20; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #135: @38 = (@9*@35) */
  for (i=0, rr=w38, cs=w35; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #136: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #137: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #138: (@36[1:4] += @37) */
  for (rr=w36+1, cs=w37; rr!=w36+4; rr+=1) *rr += *cs++;
  /* #139: @39 = (@12?@36:0) */
  for (i=0, rr=w39, cs=w36; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #140: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) *rr++ = (- *cs++ );
  /* #141: @36 = (@13?@36:0) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #142: @39 = (@39+@36) */
  for (i=0, rr=w39, cs=w36; i<4; ++i) (*rr++) += (*cs++);
  /* #143: {@17, @18, @40, @41} = vertsplit(@39) */
  w17 = w39[0];
  w18 = w39[1];
  w40 = w39[2];
  w41 = w39[3];
  /* #144: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #145: @43 = (@6*@40) */
  w43  = (w06*w40);
  /* #146: @42 = (@42+@43) */
  w42 += w43;
  /* #147: @43 = (@5*@18) */
  w43  = (w05*w18);
  /* #148: @42 = (@42+@43) */
  w42 += w43;
  /* #149: @43 = (@4*@17) */
  w43  = (w04*w17);
  /* #150: @42 = (@42+@43) */
  w42 += w43;
  /* #151: @43 = (@6*@41) */
  w43  = (w06*w41);
  /* #152: @44 = (@7*@40) */
  w44  = (w07*w40);
  /* #153: @43 = (@43-@44) */
  w43 -= w44;
  /* #154: @44 = (@4*@18) */
  w44  = (w04*w18);
  /* #155: @43 = (@43+@44) */
  w43 += w44;
  /* #156: @44 = (@5*@17) */
  w44  = (w05*w17);
  /* #157: @43 = (@43-@44) */
  w43 -= w44;
  /* #158: @44 = (@4*@40) */
  w44  = (w04*w40);
  /* #159: @45 = (@5*@41) */
  w45  = (w05*w41);
  /* #160: @44 = (@44-@45) */
  w44 -= w45;
  /* #161: @45 = (@7*@18) */
  w45  = (w07*w18);
  /* #162: @44 = (@44+@45) */
  w44 += w45;
  /* #163: @45 = (@6*@17) */
  w45  = (w06*w17);
  /* #164: @44 = (@44-@45) */
  w44 -= w45;
  /* #165: @41 = (@4*@41) */
  w41  = (w04*w41);
  /* #166: @40 = (@5*@40) */
  w40  = (w05*w40);
  /* #167: @41 = (@41+@40) */
  w41 += w40;
  /* #168: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #169: @41 = (@41-@18) */
  w41 -= w18;
  /* #170: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #171: @41 = (@41-@17) */
  w41 -= w17;
  /* #172: @39 = vertcat(@42, @43, @44, @41) */
  rr=w39;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w44;
  *rr++ = w41;
  /* #173: @42 = dot(@29, @39) */
  w42 = casadi_dot(4, w29, w39);
  /* #174: @42 = (@42/@8) */
  w42 /= w08;
  /* #175: @36 = (@42*@27) */
  for (i=0, rr=w36, cs=w27; i<4; ++i) (*rr++)  = (w42*(*cs++));
  /* #176: @46 = @21; (@46[6:10] += @36) */
  casadi_copy(w21, 13, w46);
  for (rr=w46+6, cs=w36; rr!=w46+10; rr+=1) *rr += *cs++;
  /* #177: @25 = @25' */
  /* #178: @47 = @24' */
  for (i=0, rr=w47, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #179: @37 = mac(@22,@47,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w47+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #180: @37 = @37' */
  /* #181: @25 = (@25+@37) */
  for (i=0, rr=w25, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #182: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (- *cs++ );
  /* #183: (@46[:3] += @25) */
  for (rr=w46+0, cs=w25; rr!=w46+3; rr+=1) *rr += *cs++;
  /* #184: {@43, @44, @41, @17, @18, @40, @45, @48, @49, @50, @51, @52, @53} = vertsplit(@46) */
  w43 = w46[0];
  w44 = w46[1];
  w41 = w46[2];
  w17 = w46[3];
  w18 = w46[4];
  w40 = w46[5];
  w45 = w46[6];
  w48 = w46[7];
  w49 = w46[8];
  w50 = w46[9];
  w51 = w46[10];
  w52 = w46[11];
  w53 = w46[12];
  /* #185: output[1][0] = @43 */
  if (res[1]) res[1][0] = w43;
  /* #186: output[1][1] = @44 */
  if (res[1]) res[1][1] = w44;
  /* #187: output[1][2] = @41 */
  if (res[1]) res[1][2] = w41;
  /* #188: output[1][3] = @17 */
  if (res[1]) res[1][3] = w17;
  /* #189: output[1][4] = @18 */
  if (res[1]) res[1][4] = w18;
  /* #190: output[1][5] = @40 */
  if (res[1]) res[1][5] = w40;
  /* #191: @36 = (@39/@8) */
  for (i=0, rr=w36, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #192: {@40, @18, @17, @41} = vertsplit(@36) */
  w40 = w36[0];
  w18 = w36[1];
  w17 = w36[2];
  w41 = w36[3];
  /* #193: @40 = (@40+@45) */
  w40 += w45;
  /* #194: output[1][6] = @40 */
  if (res[1]) res[1][6] = w40;
  /* #195: @48 = (@48-@18) */
  w48 -= w18;
  /* #196: output[1][7] = @48 */
  if (res[1]) res[1][7] = w48;
  /* #197: @49 = (@49-@17) */
  w49 -= w17;
  /* #198: output[1][8] = @49 */
  if (res[1]) res[1][8] = w49;
  /* #199: @50 = (@50-@41) */
  w50 -= w41;
  /* #200: output[1][9] = @50 */
  if (res[1]) res[1][9] = w50;
  /* #201: output[1][10] = @51 */
  if (res[1]) res[1][10] = w51;
  /* #202: output[1][11] = @52 */
  if (res[1]) res[1][11] = w52;
  /* #203: output[1][12] = @53 */
  if (res[1]) res[1][12] = w53;
  /* #204: @54 = zeros(13x13,25nz) */
  casadi_clear(w54, 25);
  /* #205: @55 = ones(13x1,8nz) */
  casadi_fill(w55, 8, 1.);
  /* #206: {@53, NULL, NULL, NULL, NULL, NULL, @52, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@55) */
  w53 = w55[0];
  w52 = w55[4];
  /* #207: @56 = 00 */
  /* #208: @51 = vertcat(@52, @56, @56, @56) */
  rr=(&w51);
  *rr++ = w52;
  /* #209: @51 = (@51/@8) */
  w51 /= w08;
  /* #210: @57 = dense(@51) */
  casadi_densify((&w51), casadi_s0, w57, 0);
  /* #211: @51 = project(@27) */
  casadi_sparsify(w27, (&w51), casadi_s0, 0);
  /* #212: @52 = sparsity_cast(@52) */
  /* #213: @50 = dot(@51, @52) */
  w50 = casadi_dot(1, (&w51), (&w52));
  /* #214: @50 = (@50/@8) */
  w50 /= w08;
  /* #215: @58 = (@26*@50) */
  for (i=0, rr=w58, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #216: @57 = (@57-@58) */
  for (i=0, rr=w57, cs=w58; i<4; ++i) (*rr++) -= (*cs++);
  /* #217: {@51, @41, @49, @17} = vertsplit(@57) */
  w51 = w57[0];
  w41 = w57[1];
  w49 = w57[2];
  w17 = w57[3];
  /* #218: @48 = (@4*@51) */
  w48  = (w04*w51);
  /* #219: @18 = (@5*@41) */
  w18  = (w05*w41);
  /* #220: @48 = (@48-@18) */
  w48 -= w18;
  /* #221: @18 = (@6*@49) */
  w18  = (w06*w49);
  /* #222: @48 = (@48-@18) */
  w48 -= w18;
  /* #223: @18 = (@7*@17) */
  w18  = (w07*w17);
  /* #224: @48 = (@48-@18) */
  w48 -= w18;
  /* #225: @18 = (@5*@51) */
  w18  = (w05*w51);
  /* #226: @40 = (@4*@41) */
  w40  = (w04*w41);
  /* #227: @18 = (@18+@40) */
  w18 += w40;
  /* #228: @40 = (@7*@49) */
  w40  = (w07*w49);
  /* #229: @18 = (@18+@40) */
  w18 += w40;
  /* #230: @40 = (@6*@17) */
  w40  = (w06*w17);
  /* #231: @18 = (@18-@40) */
  w18 -= w40;
  /* #232: @40 = (@6*@51) */
  w40  = (w06*w51);
  /* #233: @45 = (@7*@41) */
  w45  = (w07*w41);
  /* #234: @40 = (@40-@45) */
  w40 -= w45;
  /* #235: @45 = (@4*@49) */
  w45  = (w04*w49);
  /* #236: @40 = (@40+@45) */
  w40 += w45;
  /* #237: @45 = (@5*@17) */
  w45  = (w05*w17);
  /* #238: @40 = (@40+@45) */
  w40 += w45;
  /* #239: @51 = (@7*@51) */
  w51  = (w07*w51);
  /* #240: @41 = (@6*@41) */
  w41  = (w06*w41);
  /* #241: @51 = (@51+@41) */
  w51 += w41;
  /* #242: @49 = (@5*@49) */
  w49  = (w05*w49);
  /* #243: @51 = (@51-@49) */
  w51 -= w49;
  /* #244: @17 = (@4*@17) */
  w17  = (w04*w17);
  /* #245: @51 = (@51+@17) */
  w51 += w17;
  /* #246: @58 = vertcat(@48, @18, @40, @51) */
  rr=w58;
  *rr++ = w48;
  *rr++ = w18;
  *rr++ = w40;
  *rr++ = w51;
  /* #247: @59 = (-@58) */
  for (i=0, rr=w59, cs=w58; i<4; ++i) *rr++ = (- *cs++ );
  /* #248: @59 = (@13?@59:0) */
  for (i=0, rr=w59, cs=w59; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #249: @58 = (@12?@58:0) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #250: @59 = (@59+@58) */
  for (i=0, rr=w59, cs=w58; i<4; ++i) (*rr++) += (*cs++);
  /* #251: @25 = @59[1:4] */
  for (rr=w25, cs=w59+1; cs!=w59+4; cs+=1) *rr++ = *cs;
  /* #252: @48 = dot(@20, @25) */
  w48 = casadi_dot(3, w20, w25);
  /* #253: @48 = (@48/@14) */
  w48 /= w14;
  /* #254: @18 = (@48/@2) */
  w18  = (w48/w02);
  /* #255: @40 = (@0/@2) */
  w40  = (w00/w02);
  /* #256: @51 = (2.*@14) */
  w51 = (2.* w14 );
  /* #257: @17 = (@51*@48) */
  w17  = (w51*w48);
  /* #258: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #259: @49 = @59[0] */
  for (rr=(&w49), cs=w59+0; cs!=w59+1; cs+=1) *rr++ = *cs;
  /* #260: @41 = (@15*@49) */
  w41  = (w15*w49);
  /* #261: @17 = (@17+@41) */
  w17 += w41;
  /* #262: @41 = (@40*@17) */
  w41  = (w40*w17);
  /* #263: @18 = (@18-@41) */
  w18 -= w41;
  /* #264: @18 = (@11*@18) */
  w18  = (w11*w18);
  /* #265: @37 = (2.*@25) */
  for (i=0, rr=w37, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #266: @22 = (@9*@37) */
  for (i=0, rr=w22, cs=w37; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #267: @41 = (@16*@48) */
  w41  = (w16*w48);
  /* #268: @45 = (@0*@49) */
  w45  = (w00*w49);
  /* #269: @41 = (@41-@45) */
  w41 -= w45;
  /* #270: @38 = (@30*@41) */
  for (i=0, rr=w38, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w41);
  /* #271: @22 = (@22+@38) */
  for (i=0, rr=w22, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #272: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #273: @38 = (@31*@48) */
  for (i=0, rr=w38, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #274: @22 = (@22-@38) */
  for (i=0, rr=w22, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #275: @38 = @22' */
  casadi_copy(w22, 3, w38);
  /* #276: @60 = mac(@38,@23,@1) */
  casadi_copy(w01, 3, w60);
  for (i=0, rr=w60; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #277: @60 = @60' */
  /* #278: @61 = mac(@38,@34,@1) */
  casadi_copy(w01, 3, w61);
  for (i=0, rr=w61; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #279: @61 = @61' */
  /* #280: @60 = (@60+@61) */
  for (i=0, rr=w60, cs=w61; i<3; ++i) (*rr++) += (*cs++);
  /* #281: @61 = (@60/@3) */
  for (i=0, rr=w61, cr=w60; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #282: @38 = (@35/@3) */
  for (i=0, rr=w38, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #283: @62 = (@38*@48) */
  for (i=0, rr=w62, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #284: @61 = (@61-@62) */
  for (i=0, rr=w61, cs=w62; i<3; ++i) (*rr++) -= (*cs++);
  /* #285: @45 = dot(@30, @61) */
  w45 = casadi_dot(3, w30, w61);
  /* #286: @44 = dot(@37, @35) */
  w44 = casadi_dot(3, w37, w35);
  /* #287: @45 = (@45+@44) */
  w45 += w44;
  /* #288: @44 = (@0*@45) */
  w44  = (w00*w45);
  /* #289: @18 = (@18+@44) */
  w18 += w44;
  /* #290: @18 = (-@18) */
  w18 = (- w18 );
  /* #291: @59 = @28; (@59[0] += @18) */
  casadi_copy(w28, 4, w59);
  for (rr=w59+0, cs=(&w18); rr!=w59+1; rr+=1) *rr += *cs++;
  /* #292: @18 = dot(@32, @60) */
  w18 = casadi_dot(3, w32, w60);
  /* #293: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #294: @60 = (@31/@3) */
  for (i=0, rr=w60, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #295: @37 = (@60*@48) */
  for (i=0, rr=w37, cr=w60; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #296: @22 = (@22-@37) */
  for (i=0, rr=w22, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #297: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #298: @44 = dot(@22, @33) */
  w44 = casadi_dot(3, w22, w33);
  /* #299: @18 = (@18+@44) */
  w18 += w44;
  /* #300: @49 = (@49/@2) */
  w49 /= w02;
  /* #301: @44 = (@16/@2) */
  w44  = (w16/w02);
  /* #302: @17 = (@44*@17) */
  w17  = (w44*w17);
  /* #303: @49 = (@49-@17) */
  w49 -= w17;
  /* #304: @49 = (@11*@49) */
  w49  = (w11*w49);
  /* #305: @45 = (@16*@45) */
  w45  = (w16*w45);
  /* #306: @49 = (@49+@45) */
  w49 += w45;
  /* #307: @18 = (@18+@49) */
  w18 += w49;
  /* #308: @18 = (@18/@14) */
  w18 /= w14;
  /* #309: @49 = (@10/@14) */
  w49  = (w10/w14);
  /* #310: @48 = (@49*@48) */
  w48  = (w49*w48);
  /* #311: @18 = (@18-@48) */
  w18 -= w48;
  /* #312: @22 = (@20*@18) */
  for (i=0, rr=w22, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #313: @25 = (@10*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #314: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #315: @25 = (@35*@41) */
  for (i=0, rr=w25, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w41);
  /* #316: @61 = (@9*@61) */
  for (i=0, rr=w61, cs=w61; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #317: @25 = (@25+@61) */
  for (i=0, rr=w25, cs=w61; i<3; ++i) (*rr++) += (*cs++);
  /* #318: @25 = (2.*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #319: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #320: (@59[1:4] += @22) */
  for (rr=w59+1, cs=w22; rr!=w59+4; rr+=1) *rr += *cs++;
  /* #321: @58 = (@12?@59:0) */
  for (i=0, rr=w58, cs=w59; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #322: @59 = (-@59) */
  for (i=0, rr=w59, cs=w59; i<4; ++i) *rr++ = (- *cs++ );
  /* #323: @59 = (@13?@59:0) */
  for (i=0, rr=w59, cs=w59; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #324: @58 = (@58+@59) */
  for (i=0, rr=w58, cs=w59; i<4; ++i) (*rr++) += (*cs++);
  /* #325: {@41, @18, @48, @45} = vertsplit(@58) */
  w41 = w58[0];
  w18 = w58[1];
  w48 = w58[2];
  w45 = w58[3];
  /* #326: @17 = (@7*@45) */
  w17  = (w07*w45);
  /* #327: @43 = (@6*@48) */
  w43  = (w06*w48);
  /* #328: @17 = (@17+@43) */
  w17 += w43;
  /* #329: @43 = (@5*@18) */
  w43  = (w05*w18);
  /* #330: @17 = (@17+@43) */
  w17 += w43;
  /* #331: @43 = (@4*@41) */
  w43  = (w04*w41);
  /* #332: @17 = (@17+@43) */
  w17 += w43;
  /* #333: @43 = (@6*@45) */
  w43  = (w06*w45);
  /* #334: @63 = (@7*@48) */
  w63  = (w07*w48);
  /* #335: @43 = (@43-@63) */
  w43 -= w63;
  /* #336: @63 = (@4*@18) */
  w63  = (w04*w18);
  /* #337: @43 = (@43+@63) */
  w43 += w63;
  /* #338: @63 = (@5*@41) */
  w63  = (w05*w41);
  /* #339: @43 = (@43-@63) */
  w43 -= w63;
  /* #340: @63 = (@4*@48) */
  w63  = (w04*w48);
  /* #341: @64 = (@5*@45) */
  w64  = (w05*w45);
  /* #342: @63 = (@63-@64) */
  w63 -= w64;
  /* #343: @64 = (@7*@18) */
  w64  = (w07*w18);
  /* #344: @63 = (@63+@64) */
  w63 += w64;
  /* #345: @64 = (@6*@41) */
  w64  = (w06*w41);
  /* #346: @63 = (@63-@64) */
  w63 -= w64;
  /* #347: @45 = (@4*@45) */
  w45  = (w04*w45);
  /* #348: @48 = (@5*@48) */
  w48  = (w05*w48);
  /* #349: @45 = (@45+@48) */
  w45 += w48;
  /* #350: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #351: @45 = (@45-@18) */
  w45 -= w18;
  /* #352: @41 = (@7*@41) */
  w41  = (w07*w41);
  /* #353: @45 = (@45-@41) */
  w45 -= w41;
  /* #354: @58 = vertcat(@17, @43, @63, @45) */
  rr=w58;
  *rr++ = w17;
  *rr++ = w43;
  *rr++ = w63;
  *rr++ = w45;
  /* #355: @17 = dot(@29, @58) */
  w17 = casadi_dot(4, w29, w58);
  /* #356: @57 = (@57/@8) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w08;
  /* #357: @59 = (@26/@8) */
  for (i=0, rr=w59, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #358: @65 = (@59*@50) */
  for (i=0, rr=w65, cr=w59; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #359: @57 = (@57-@65) */
  for (i=0, rr=w57, cs=w65; i<4; ++i) (*rr++) -= (*cs++);
  /* #360: @57 = (-@57) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #361: @43 = dot(@57, @39) */
  w43 = casadi_dot(4, w57, w39);
  /* #362: @17 = (@17+@43) */
  w17 += w43;
  /* #363: @17 = (@17/@8) */
  w17 /= w08;
  /* #364: @43 = (@42/@8) */
  w43  = (w42/w08);
  /* #365: @63 = (@43*@50) */
  w63  = (w43*w50);
  /* #366: @17 = (@17-@63) */
  w17 -= w63;
  /* #367: @57 = (@27*@17) */
  for (i=0, rr=w57, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #368: @52 = (@42*@52) */
  w52  = (w42*w52);
  /* #369: @65 = dense(@52) */
  casadi_densify((&w52), casadi_s0, w65, 0);
  /* #370: @57 = (@57+@65) */
  for (i=0, rr=w57, cs=w65; i<4; ++i) (*rr++) += (*cs++);
  /* #371: @46 = @21; (@46[6:10] += @57) */
  casadi_copy(w21, 13, w46);
  for (rr=w46+6, cs=w57; rr!=w46+10; rr+=1) *rr += *cs++;
  /* #372: @53 = sparsity_cast(@53) */
  /* #373: @53 = (-@53) */
  w53 = (- w53 );
  /* #374: @53 = @53' */
  /* #375: @22 = mac(@53,@24,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w53), casadi_s3, w24, casadi_s2, w22, casadi_s1, w, 0);
  /* #376: @22 = @22' */
  /* #377: @25 = mac(@53,@47,@1) */
  casadi_copy(w01, 3, w25);
  casadi_mtimes((&w53), casadi_s3, w47, casadi_s2, w25, casadi_s1, w, 0);
  /* #378: @25 = @25' */
  /* #379: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #380: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #381: (@46[:3] += @22) */
  for (rr=w46+0, cs=w22; rr!=w46+3; rr+=1) *rr += *cs++;
  /* #382: {@53, @52, @17, @63, @45, @41, @18, @48, @64, @66, @67, @68, @69} = vertsplit(@46) */
  w53 = w46[0];
  w52 = w46[1];
  w17 = w46[2];
  w63 = w46[3];
  w45 = w46[4];
  w41 = w46[5];
  w18 = w46[6];
  w48 = w46[7];
  w64 = w46[8];
  w66 = w46[9];
  w67 = w46[10];
  w68 = w46[11];
  w69 = w46[12];
  /* #383: @58 = (@58/@8) */
  for (i=0, rr=w58; i<4; ++i) (*rr++) /= w08;
  /* #384: @36 = (@36/@8) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) /= w08;
  /* #385: @57 = (@36*@50) */
  for (i=0, rr=w57, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #386: @58 = (@58-@57) */
  for (i=0, rr=w58, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #387: {@50, @70, @71, @72} = vertsplit(@58) */
  w50 = w58[0];
  w70 = w58[1];
  w71 = w58[2];
  w72 = w58[3];
  /* #388: @50 = (@50+@18) */
  w50 += w18;
  /* #389: @48 = (@48-@70) */
  w48 -= w70;
  /* #390: @64 = (@64-@71) */
  w64 -= w71;
  /* #391: @66 = (@66-@72) */
  w66 -= w72;
  /* #392: @46 = vertcat(@53, @52, @17, @63, @45, @41, @50, @48, @64, @66, @67, @68, @69) */
  rr=w46;
  *rr++ = w53;
  *rr++ = w52;
  *rr++ = w17;
  *rr++ = w63;
  *rr++ = w45;
  *rr++ = w41;
  *rr++ = w50;
  *rr++ = w48;
  *rr++ = w64;
  *rr++ = w66;
  *rr++ = w67;
  *rr++ = w68;
  *rr++ = w69;
  /* #393: @73 = @46[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w73, cs=w46; cii!=casadi_s4+7; ++cii) *rr++ = cs[*cii];
  /* #394: (@54[0, 1, 2, 9, 10, 11, 12] = @73) */
  for (cii=casadi_s5, rr=w54, cs=w73; cii!=casadi_s5+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #395: (@54[0, 3, 6, 9, 13, 17, 21] = @73) */
  for (cii=casadi_s6, rr=w54, cs=w73; cii!=casadi_s6+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #396: @74 = ones(13x1,2nz) */
  casadi_fill(w74, 2, 1.);
  /* #397: {NULL, @53, NULL, NULL, NULL, NULL, NULL, @52, NULL, NULL, NULL, NULL, NULL} = vertsplit(@74) */
  w53 = w74[0];
  w52 = w74[1];
  /* #398: @17 = (-@52) */
  w17 = (- w52 );
  /* #399: @63 = vertcat(@56, @17, @56, @56) */
  rr=(&w63);
  *rr++ = w17;
  /* #400: @63 = (@63/@8) */
  w63 /= w08;
  /* #401: @58 = dense(@63) */
  casadi_densify((&w63), casadi_s7, w58, 0);
  /* #402: @63 = project(@27) */
  casadi_sparsify(w27, (&w63), casadi_s7, 0);
  /* #403: @52 = sparsity_cast(@52) */
  /* #404: @17 = dot(@63, @52) */
  w17 = casadi_dot(1, (&w63), (&w52));
  /* #405: @17 = (@17/@8) */
  w17 /= w08;
  /* #406: @57 = (@26*@17) */
  for (i=0, rr=w57, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #407: @58 = (@58-@57) */
  for (i=0, rr=w58, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #408: {@63, @45, @41, @50} = vertsplit(@58) */
  w63 = w58[0];
  w45 = w58[1];
  w41 = w58[2];
  w50 = w58[3];
  /* #409: @48 = (@4*@63) */
  w48  = (w04*w63);
  /* #410: @64 = (@5*@45) */
  w64  = (w05*w45);
  /* #411: @48 = (@48-@64) */
  w48 -= w64;
  /* #412: @64 = (@6*@41) */
  w64  = (w06*w41);
  /* #413: @48 = (@48-@64) */
  w48 -= w64;
  /* #414: @64 = (@7*@50) */
  w64  = (w07*w50);
  /* #415: @48 = (@48-@64) */
  w48 -= w64;
  /* #416: @64 = (@5*@63) */
  w64  = (w05*w63);
  /* #417: @66 = (@4*@45) */
  w66  = (w04*w45);
  /* #418: @64 = (@64+@66) */
  w64 += w66;
  /* #419: @66 = (@7*@41) */
  w66  = (w07*w41);
  /* #420: @64 = (@64+@66) */
  w64 += w66;
  /* #421: @66 = (@6*@50) */
  w66  = (w06*w50);
  /* #422: @64 = (@64-@66) */
  w64 -= w66;
  /* #423: @66 = (@6*@63) */
  w66  = (w06*w63);
  /* #424: @67 = (@7*@45) */
  w67  = (w07*w45);
  /* #425: @66 = (@66-@67) */
  w66 -= w67;
  /* #426: @67 = (@4*@41) */
  w67  = (w04*w41);
  /* #427: @66 = (@66+@67) */
  w66 += w67;
  /* #428: @67 = (@5*@50) */
  w67  = (w05*w50);
  /* #429: @66 = (@66+@67) */
  w66 += w67;
  /* #430: @63 = (@7*@63) */
  w63  = (w07*w63);
  /* #431: @45 = (@6*@45) */
  w45  = (w06*w45);
  /* #432: @63 = (@63+@45) */
  w63 += w45;
  /* #433: @41 = (@5*@41) */
  w41  = (w05*w41);
  /* #434: @63 = (@63-@41) */
  w63 -= w41;
  /* #435: @50 = (@4*@50) */
  w50  = (w04*w50);
  /* #436: @63 = (@63+@50) */
  w63 += w50;
  /* #437: @57 = vertcat(@48, @64, @66, @63) */
  rr=w57;
  *rr++ = w48;
  *rr++ = w64;
  *rr++ = w66;
  *rr++ = w63;
  /* #438: @65 = (-@57) */
  for (i=0, rr=w65, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #439: @65 = (@13?@65:0) */
  for (i=0, rr=w65, cs=w65; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #440: @57 = (@12?@57:0) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #441: @65 = (@65+@57) */
  for (i=0, rr=w65, cs=w57; i<4; ++i) (*rr++) += (*cs++);
  /* #442: @22 = @65[1:4] */
  for (rr=w22, cs=w65+1; cs!=w65+4; cs+=1) *rr++ = *cs;
  /* #443: @48 = dot(@20, @22) */
  w48 = casadi_dot(3, w20, w22);
  /* #444: @48 = (@48/@14) */
  w48 /= w14;
  /* #445: @64 = (@48/@2) */
  w64  = (w48/w02);
  /* #446: @66 = (@51*@48) */
  w66  = (w51*w48);
  /* #447: @63 = @65[0] */
  for (rr=(&w63), cs=w65+0; cs!=w65+1; cs+=1) *rr++ = *cs;
  /* #448: @50 = (@15*@63) */
  w50  = (w15*w63);
  /* #449: @66 = (@66+@50) */
  w66 += w50;
  /* #450: @50 = (@40*@66) */
  w50  = (w40*w66);
  /* #451: @64 = (@64-@50) */
  w64 -= w50;
  /* #452: @64 = (@11*@64) */
  w64  = (w11*w64);
  /* #453: @25 = (2.*@22) */
  for (i=0, rr=w25, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #454: @61 = (@9*@25) */
  for (i=0, rr=w61, cs=w25; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #455: @50 = (@16*@48) */
  w50  = (w16*w48);
  /* #456: @41 = (@0*@63) */
  w41  = (w00*w63);
  /* #457: @50 = (@50-@41) */
  w50 -= w41;
  /* #458: @37 = (@30*@50) */
  for (i=0, rr=w37, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w50);
  /* #459: @61 = (@61+@37) */
  for (i=0, rr=w61, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #460: @61 = (@61/@3) */
  for (i=0, rr=w61; i<3; ++i) (*rr++) /= w03;
  /* #461: @37 = (@31*@48) */
  for (i=0, rr=w37, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #462: @61 = (@61-@37) */
  for (i=0, rr=w61, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #463: @37 = @61' */
  casadi_copy(w61, 3, w37);
  /* #464: @62 = mac(@37,@23,@1) */
  casadi_copy(w01, 3, w62);
  for (i=0, rr=w62; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #465: @62 = @62' */
  /* #466: @75 = mac(@37,@34,@1) */
  casadi_copy(w01, 3, w75);
  for (i=0, rr=w75; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #467: @75 = @75' */
  /* #468: @62 = (@62+@75) */
  for (i=0, rr=w62, cs=w75; i<3; ++i) (*rr++) += (*cs++);
  /* #469: @75 = (@62/@3) */
  for (i=0, rr=w75, cr=w62; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #470: @37 = (@38*@48) */
  for (i=0, rr=w37, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #471: @75 = (@75-@37) */
  for (i=0, rr=w75, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #472: @41 = dot(@30, @75) */
  w41 = casadi_dot(3, w30, w75);
  /* #473: @45 = dot(@25, @35) */
  w45 = casadi_dot(3, w25, w35);
  /* #474: @41 = (@41+@45) */
  w41 += w45;
  /* #475: @45 = (@0*@41) */
  w45  = (w00*w41);
  /* #476: @64 = (@64+@45) */
  w64 += w45;
  /* #477: @64 = (-@64) */
  w64 = (- w64 );
  /* #478: @65 = @28; (@65[0] += @64) */
  casadi_copy(w28, 4, w65);
  for (rr=w65+0, cs=(&w64); rr!=w65+1; rr+=1) *rr += *cs++;
  /* #479: @64 = dot(@32, @62) */
  w64 = casadi_dot(3, w32, w62);
  /* #480: @61 = (@61/@3) */
  for (i=0, rr=w61; i<3; ++i) (*rr++) /= w03;
  /* #481: @62 = (@60*@48) */
  for (i=0, rr=w62, cr=w60; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #482: @61 = (@61-@62) */
  for (i=0, rr=w61, cs=w62; i<3; ++i) (*rr++) -= (*cs++);
  /* #483: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<3; ++i) *rr++ = (- *cs++ );
  /* #484: @45 = dot(@61, @33) */
  w45 = casadi_dot(3, w61, w33);
  /* #485: @64 = (@64+@45) */
  w64 += w45;
  /* #486: @63 = (@63/@2) */
  w63 /= w02;
  /* #487: @66 = (@44*@66) */
  w66  = (w44*w66);
  /* #488: @63 = (@63-@66) */
  w63 -= w66;
  /* #489: @63 = (@11*@63) */
  w63  = (w11*w63);
  /* #490: @41 = (@16*@41) */
  w41  = (w16*w41);
  /* #491: @63 = (@63+@41) */
  w63 += w41;
  /* #492: @64 = (@64+@63) */
  w64 += w63;
  /* #493: @64 = (@64/@14) */
  w64 /= w14;
  /* #494: @48 = (@49*@48) */
  w48  = (w49*w48);
  /* #495: @64 = (@64-@48) */
  w64 -= w48;
  /* #496: @61 = (@20*@64) */
  for (i=0, rr=w61, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w64);
  /* #497: @22 = (@10*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #498: @61 = (@61+@22) */
  for (i=0, rr=w61, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #499: @22 = (@35*@50) */
  for (i=0, rr=w22, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w50);
  /* #500: @75 = (@9*@75) */
  for (i=0, rr=w75, cs=w75; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #501: @22 = (@22+@75) */
  for (i=0, rr=w22, cs=w75; i<3; ++i) (*rr++) += (*cs++);
  /* #502: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #503: @61 = (@61+@22) */
  for (i=0, rr=w61, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #504: (@65[1:4] += @61) */
  for (rr=w65+1, cs=w61; rr!=w65+4; rr+=1) *rr += *cs++;
  /* #505: @57 = (@12?@65:0) */
  for (i=0, rr=w57, cs=w65; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #506: @65 = (-@65) */
  for (i=0, rr=w65, cs=w65; i<4; ++i) *rr++ = (- *cs++ );
  /* #507: @65 = (@13?@65:0) */
  for (i=0, rr=w65, cs=w65; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #508: @57 = (@57+@65) */
  for (i=0, rr=w57, cs=w65; i<4; ++i) (*rr++) += (*cs++);
  /* #509: {@50, @64, @48, @63} = vertsplit(@57) */
  w50 = w57[0];
  w64 = w57[1];
  w48 = w57[2];
  w63 = w57[3];
  /* #510: @41 = (@7*@63) */
  w41  = (w07*w63);
  /* #511: @66 = (@6*@48) */
  w66  = (w06*w48);
  /* #512: @41 = (@41+@66) */
  w41 += w66;
  /* #513: @66 = (@5*@64) */
  w66  = (w05*w64);
  /* #514: @41 = (@41+@66) */
  w41 += w66;
  /* #515: @66 = (@4*@50) */
  w66  = (w04*w50);
  /* #516: @41 = (@41+@66) */
  w41 += w66;
  /* #517: @66 = (@6*@63) */
  w66  = (w06*w63);
  /* #518: @45 = (@7*@48) */
  w45  = (w07*w48);
  /* #519: @66 = (@66-@45) */
  w66 -= w45;
  /* #520: @45 = (@4*@64) */
  w45  = (w04*w64);
  /* #521: @66 = (@66+@45) */
  w66 += w45;
  /* #522: @45 = (@5*@50) */
  w45  = (w05*w50);
  /* #523: @66 = (@66-@45) */
  w66 -= w45;
  /* #524: @45 = (@4*@48) */
  w45  = (w04*w48);
  /* #525: @67 = (@5*@63) */
  w67  = (w05*w63);
  /* #526: @45 = (@45-@67) */
  w45 -= w67;
  /* #527: @67 = (@7*@64) */
  w67  = (w07*w64);
  /* #528: @45 = (@45+@67) */
  w45 += w67;
  /* #529: @67 = (@6*@50) */
  w67  = (w06*w50);
  /* #530: @45 = (@45-@67) */
  w45 -= w67;
  /* #531: @63 = (@4*@63) */
  w63  = (w04*w63);
  /* #532: @48 = (@5*@48) */
  w48  = (w05*w48);
  /* #533: @63 = (@63+@48) */
  w63 += w48;
  /* #534: @64 = (@6*@64) */
  w64  = (w06*w64);
  /* #535: @63 = (@63-@64) */
  w63 -= w64;
  /* #536: @50 = (@7*@50) */
  w50  = (w07*w50);
  /* #537: @63 = (@63-@50) */
  w63 -= w50;
  /* #538: @57 = vertcat(@41, @66, @45, @63) */
  rr=w57;
  *rr++ = w41;
  *rr++ = w66;
  *rr++ = w45;
  *rr++ = w63;
  /* #539: @41 = dot(@29, @57) */
  w41 = casadi_dot(4, w29, w57);
  /* #540: @58 = (@58/@8) */
  for (i=0, rr=w58; i<4; ++i) (*rr++) /= w08;
  /* #541: @65 = (@59*@17) */
  for (i=0, rr=w65, cr=w59; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #542: @58 = (@58-@65) */
  for (i=0, rr=w58, cs=w65; i<4; ++i) (*rr++) -= (*cs++);
  /* #543: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) *rr++ = (- *cs++ );
  /* #544: @66 = dot(@58, @39) */
  w66 = casadi_dot(4, w58, w39);
  /* #545: @41 = (@41+@66) */
  w41 += w66;
  /* #546: @41 = (@41/@8) */
  w41 /= w08;
  /* #547: @66 = (@43*@17) */
  w66  = (w43*w17);
  /* #548: @41 = (@41-@66) */
  w41 -= w66;
  /* #549: @58 = (@27*@41) */
  for (i=0, rr=w58, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w41);
  /* #550: @52 = (@42*@52) */
  w52  = (w42*w52);
  /* #551: @65 = dense(@52) */
  casadi_densify((&w52), casadi_s7, w65, 0);
  /* #552: @58 = (@58+@65) */
  for (i=0, rr=w58, cs=w65; i<4; ++i) (*rr++) += (*cs++);
  /* #553: @46 = @21; (@46[6:10] += @58) */
  casadi_copy(w21, 13, w46);
  for (rr=w46+6, cs=w58; rr!=w46+10; rr+=1) *rr += *cs++;
  /* #554: @53 = sparsity_cast(@53) */
  /* #555: @53 = (-@53) */
  w53 = (- w53 );
  /* #556: @53 = @53' */
  /* #557: @61 = mac(@53,@24,@1) */
  casadi_copy(w01, 3, w61);
  casadi_mtimes((&w53), casadi_s8, w24, casadi_s2, w61, casadi_s1, w, 0);
  /* #558: @61 = @61' */
  /* #559: @22 = mac(@53,@47,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w53), casadi_s8, w47, casadi_s2, w22, casadi_s1, w, 0);
  /* #560: @22 = @22' */
  /* #561: @61 = (@61+@22) */
  for (i=0, rr=w61, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #562: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<3; ++i) *rr++ = (- *cs++ );
  /* #563: (@46[:3] += @61) */
  for (rr=w46+0, cs=w61; rr!=w46+3; rr+=1) *rr += *cs++;
  /* #564: {@53, @52, @41, @66, @45, @63, @50, @64, @48, @67, @68, @69, @72} = vertsplit(@46) */
  w53 = w46[0];
  w52 = w46[1];
  w41 = w46[2];
  w66 = w46[3];
  w45 = w46[4];
  w63 = w46[5];
  w50 = w46[6];
  w64 = w46[7];
  w48 = w46[8];
  w67 = w46[9];
  w68 = w46[10];
  w69 = w46[11];
  w72 = w46[12];
  /* #565: @57 = (@57/@8) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w08;
  /* #566: @58 = (@36*@17) */
  for (i=0, rr=w58, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #567: @57 = (@57-@58) */
  for (i=0, rr=w57, cs=w58; i<4; ++i) (*rr++) -= (*cs++);
  /* #568: {@17, @71, @70, @18} = vertsplit(@57) */
  w17 = w57[0];
  w71 = w57[1];
  w70 = w57[2];
  w18 = w57[3];
  /* #569: @17 = (@17+@50) */
  w17 += w50;
  /* #570: @64 = (@64-@71) */
  w64 -= w71;
  /* #571: @48 = (@48-@70) */
  w48 -= w70;
  /* #572: @67 = (@67-@18) */
  w67 -= w18;
  /* #573: @46 = vertcat(@53, @52, @41, @66, @45, @63, @17, @64, @48, @67, @68, @69, @72) */
  rr=w46;
  *rr++ = w53;
  *rr++ = w52;
  *rr++ = w41;
  *rr++ = w66;
  *rr++ = w45;
  *rr++ = w63;
  *rr++ = w17;
  *rr++ = w64;
  *rr++ = w48;
  *rr++ = w67;
  *rr++ = w68;
  *rr++ = w69;
  *rr++ = w72;
  /* #574: @73 = @46[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w73, cs=w46; cii!=casadi_s4+7; ++cii) *rr++ = cs[*cii];
  /* #575: (@54[3, 4, 5, 13, 14, 15, 16] = @73) */
  for (cii=casadi_s9, rr=w54, cs=w73; cii!=casadi_s9+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #576: (@54[1, 4, 7, 10, 14, 18, 22] = @73) */
  for (cii=casadi_s10, rr=w54, cs=w73; cii!=casadi_s10+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #577: @74 = ones(13x1,2nz) */
  casadi_fill(w74, 2, 1.);
  /* #578: {NULL, NULL, @53, NULL, NULL, NULL, NULL, NULL, @52, NULL, NULL, NULL, NULL} = vertsplit(@74) */
  w53 = w74[0];
  w52 = w74[1];
  /* #579: @41 = (-@52) */
  w41 = (- w52 );
  /* #580: @66 = vertcat(@56, @56, @41, @56) */
  rr=(&w66);
  *rr++ = w41;
  /* #581: @66 = (@66/@8) */
  w66 /= w08;
  /* #582: @57 = dense(@66) */
  casadi_densify((&w66), casadi_s11, w57, 0);
  /* #583: @66 = project(@27) */
  casadi_sparsify(w27, (&w66), casadi_s11, 0);
  /* #584: @52 = sparsity_cast(@52) */
  /* #585: @41 = dot(@66, @52) */
  w41 = casadi_dot(1, (&w66), (&w52));
  /* #586: @41 = (@41/@8) */
  w41 /= w08;
  /* #587: @58 = (@26*@41) */
  for (i=0, rr=w58, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w41);
  /* #588: @57 = (@57-@58) */
  for (i=0, rr=w57, cs=w58; i<4; ++i) (*rr++) -= (*cs++);
  /* #589: {@66, @45, @63, @17} = vertsplit(@57) */
  w66 = w57[0];
  w45 = w57[1];
  w63 = w57[2];
  w17 = w57[3];
  /* #590: @64 = (@4*@66) */
  w64  = (w04*w66);
  /* #591: @48 = (@5*@45) */
  w48  = (w05*w45);
  /* #592: @64 = (@64-@48) */
  w64 -= w48;
  /* #593: @48 = (@6*@63) */
  w48  = (w06*w63);
  /* #594: @64 = (@64-@48) */
  w64 -= w48;
  /* #595: @48 = (@7*@17) */
  w48  = (w07*w17);
  /* #596: @64 = (@64-@48) */
  w64 -= w48;
  /* #597: @48 = (@5*@66) */
  w48  = (w05*w66);
  /* #598: @67 = (@4*@45) */
  w67  = (w04*w45);
  /* #599: @48 = (@48+@67) */
  w48 += w67;
  /* #600: @67 = (@7*@63) */
  w67  = (w07*w63);
  /* #601: @48 = (@48+@67) */
  w48 += w67;
  /* #602: @67 = (@6*@17) */
  w67  = (w06*w17);
  /* #603: @48 = (@48-@67) */
  w48 -= w67;
  /* #604: @67 = (@6*@66) */
  w67  = (w06*w66);
  /* #605: @68 = (@7*@45) */
  w68  = (w07*w45);
  /* #606: @67 = (@67-@68) */
  w67 -= w68;
  /* #607: @68 = (@4*@63) */
  w68  = (w04*w63);
  /* #608: @67 = (@67+@68) */
  w67 += w68;
  /* #609: @68 = (@5*@17) */
  w68  = (w05*w17);
  /* #610: @67 = (@67+@68) */
  w67 += w68;
  /* #611: @66 = (@7*@66) */
  w66  = (w07*w66);
  /* #612: @45 = (@6*@45) */
  w45  = (w06*w45);
  /* #613: @66 = (@66+@45) */
  w66 += w45;
  /* #614: @63 = (@5*@63) */
  w63  = (w05*w63);
  /* #615: @66 = (@66-@63) */
  w66 -= w63;
  /* #616: @17 = (@4*@17) */
  w17  = (w04*w17);
  /* #617: @66 = (@66+@17) */
  w66 += w17;
  /* #618: @58 = vertcat(@64, @48, @67, @66) */
  rr=w58;
  *rr++ = w64;
  *rr++ = w48;
  *rr++ = w67;
  *rr++ = w66;
  /* #619: @65 = (-@58) */
  for (i=0, rr=w65, cs=w58; i<4; ++i) *rr++ = (- *cs++ );
  /* #620: @65 = (@13?@65:0) */
  for (i=0, rr=w65, cs=w65; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #621: @58 = (@12?@58:0) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #622: @65 = (@65+@58) */
  for (i=0, rr=w65, cs=w58; i<4; ++i) (*rr++) += (*cs++);
  /* #623: @61 = @65[1:4] */
  for (rr=w61, cs=w65+1; cs!=w65+4; cs+=1) *rr++ = *cs;
  /* #624: @64 = dot(@20, @61) */
  w64 = casadi_dot(3, w20, w61);
  /* #625: @64 = (@64/@14) */
  w64 /= w14;
  /* #626: @48 = (@64/@2) */
  w48  = (w64/w02);
  /* #627: @67 = (@51*@64) */
  w67  = (w51*w64);
  /* #628: @66 = @65[0] */
  for (rr=(&w66), cs=w65+0; cs!=w65+1; cs+=1) *rr++ = *cs;
  /* #629: @17 = (@15*@66) */
  w17  = (w15*w66);
  /* #630: @67 = (@67+@17) */
  w67 += w17;
  /* #631: @17 = (@40*@67) */
  w17  = (w40*w67);
  /* #632: @48 = (@48-@17) */
  w48 -= w17;
  /* #633: @48 = (@11*@48) */
  w48  = (w11*w48);
  /* #634: @22 = (2.*@61) */
  for (i=0, rr=w22, cs=w61; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #635: @75 = (@9*@22) */
  for (i=0, rr=w75, cs=w22; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #636: @17 = (@16*@64) */
  w17  = (w16*w64);
  /* #637: @63 = (@0*@66) */
  w63  = (w00*w66);
  /* #638: @17 = (@17-@63) */
  w17 -= w63;
  /* #639: @62 = (@30*@17) */
  for (i=0, rr=w62, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #640: @75 = (@75+@62) */
  for (i=0, rr=w75, cs=w62; i<3; ++i) (*rr++) += (*cs++);
  /* #641: @75 = (@75/@3) */
  for (i=0, rr=w75; i<3; ++i) (*rr++) /= w03;
  /* #642: @62 = (@31*@64) */
  for (i=0, rr=w62, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w64);
  /* #643: @75 = (@75-@62) */
  for (i=0, rr=w75, cs=w62; i<3; ++i) (*rr++) -= (*cs++);
  /* #644: @62 = @75' */
  casadi_copy(w75, 3, w62);
  /* #645: @25 = mac(@62,@23,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w62+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #646: @25 = @25' */
  /* #647: @37 = mac(@62,@34,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w62+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #648: @37 = @37' */
  /* #649: @25 = (@25+@37) */
  for (i=0, rr=w25, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #650: @37 = (@25/@3) */
  for (i=0, rr=w37, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #651: @62 = (@38*@64) */
  for (i=0, rr=w62, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w64);
  /* #652: @37 = (@37-@62) */
  for (i=0, rr=w37, cs=w62; i<3; ++i) (*rr++) -= (*cs++);
  /* #653: @63 = dot(@30, @37) */
  w63 = casadi_dot(3, w30, w37);
  /* #654: @45 = dot(@22, @35) */
  w45 = casadi_dot(3, w22, w35);
  /* #655: @63 = (@63+@45) */
  w63 += w45;
  /* #656: @45 = (@0*@63) */
  w45  = (w00*w63);
  /* #657: @48 = (@48+@45) */
  w48 += w45;
  /* #658: @48 = (-@48) */
  w48 = (- w48 );
  /* #659: @65 = @28; (@65[0] += @48) */
  casadi_copy(w28, 4, w65);
  for (rr=w65+0, cs=(&w48); rr!=w65+1; rr+=1) *rr += *cs++;
  /* #660: @48 = dot(@32, @25) */
  w48 = casadi_dot(3, w32, w25);
  /* #661: @75 = (@75/@3) */
  for (i=0, rr=w75; i<3; ++i) (*rr++) /= w03;
  /* #662: @25 = (@60*@64) */
  for (i=0, rr=w25, cr=w60; i<3; ++i) (*rr++)  = ((*cr++)*w64);
  /* #663: @75 = (@75-@25) */
  for (i=0, rr=w75, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #664: @75 = (-@75) */
  for (i=0, rr=w75, cs=w75; i<3; ++i) *rr++ = (- *cs++ );
  /* #665: @45 = dot(@75, @33) */
  w45 = casadi_dot(3, w75, w33);
  /* #666: @48 = (@48+@45) */
  w48 += w45;
  /* #667: @66 = (@66/@2) */
  w66 /= w02;
  /* #668: @67 = (@44*@67) */
  w67  = (w44*w67);
  /* #669: @66 = (@66-@67) */
  w66 -= w67;
  /* #670: @66 = (@11*@66) */
  w66  = (w11*w66);
  /* #671: @63 = (@16*@63) */
  w63  = (w16*w63);
  /* #672: @66 = (@66+@63) */
  w66 += w63;
  /* #673: @48 = (@48+@66) */
  w48 += w66;
  /* #674: @48 = (@48/@14) */
  w48 /= w14;
  /* #675: @64 = (@49*@64) */
  w64  = (w49*w64);
  /* #676: @48 = (@48-@64) */
  w48 -= w64;
  /* #677: @75 = (@20*@48) */
  for (i=0, rr=w75, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #678: @61 = (@10*@61) */
  for (i=0, rr=w61, cs=w61; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #679: @75 = (@75+@61) */
  for (i=0, rr=w75, cs=w61; i<3; ++i) (*rr++) += (*cs++);
  /* #680: @61 = (@35*@17) */
  for (i=0, rr=w61, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #681: @37 = (@9*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #682: @61 = (@61+@37) */
  for (i=0, rr=w61, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #683: @61 = (2.*@61) */
  for (i=0, rr=w61, cs=w61; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #684: @75 = (@75+@61) */
  for (i=0, rr=w75, cs=w61; i<3; ++i) (*rr++) += (*cs++);
  /* #685: (@65[1:4] += @75) */
  for (rr=w65+1, cs=w75; rr!=w65+4; rr+=1) *rr += *cs++;
  /* #686: @58 = (@12?@65:0) */
  for (i=0, rr=w58, cs=w65; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #687: @65 = (-@65) */
  for (i=0, rr=w65, cs=w65; i<4; ++i) *rr++ = (- *cs++ );
  /* #688: @65 = (@13?@65:0) */
  for (i=0, rr=w65, cs=w65; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #689: @58 = (@58+@65) */
  for (i=0, rr=w58, cs=w65; i<4; ++i) (*rr++) += (*cs++);
  /* #690: {@17, @48, @64, @66} = vertsplit(@58) */
  w17 = w58[0];
  w48 = w58[1];
  w64 = w58[2];
  w66 = w58[3];
  /* #691: @63 = (@7*@66) */
  w63  = (w07*w66);
  /* #692: @67 = (@6*@64) */
  w67  = (w06*w64);
  /* #693: @63 = (@63+@67) */
  w63 += w67;
  /* #694: @67 = (@5*@48) */
  w67  = (w05*w48);
  /* #695: @63 = (@63+@67) */
  w63 += w67;
  /* #696: @67 = (@4*@17) */
  w67  = (w04*w17);
  /* #697: @63 = (@63+@67) */
  w63 += w67;
  /* #698: @67 = (@6*@66) */
  w67  = (w06*w66);
  /* #699: @45 = (@7*@64) */
  w45  = (w07*w64);
  /* #700: @67 = (@67-@45) */
  w67 -= w45;
  /* #701: @45 = (@4*@48) */
  w45  = (w04*w48);
  /* #702: @67 = (@67+@45) */
  w67 += w45;
  /* #703: @45 = (@5*@17) */
  w45  = (w05*w17);
  /* #704: @67 = (@67-@45) */
  w67 -= w45;
  /* #705: @45 = (@4*@64) */
  w45  = (w04*w64);
  /* #706: @68 = (@5*@66) */
  w68  = (w05*w66);
  /* #707: @45 = (@45-@68) */
  w45 -= w68;
  /* #708: @68 = (@7*@48) */
  w68  = (w07*w48);
  /* #709: @45 = (@45+@68) */
  w45 += w68;
  /* #710: @68 = (@6*@17) */
  w68  = (w06*w17);
  /* #711: @45 = (@45-@68) */
  w45 -= w68;
  /* #712: @66 = (@4*@66) */
  w66  = (w04*w66);
  /* #713: @64 = (@5*@64) */
  w64  = (w05*w64);
  /* #714: @66 = (@66+@64) */
  w66 += w64;
  /* #715: @48 = (@6*@48) */
  w48  = (w06*w48);
  /* #716: @66 = (@66-@48) */
  w66 -= w48;
  /* #717: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #718: @66 = (@66-@17) */
  w66 -= w17;
  /* #719: @58 = vertcat(@63, @67, @45, @66) */
  rr=w58;
  *rr++ = w63;
  *rr++ = w67;
  *rr++ = w45;
  *rr++ = w66;
  /* #720: @63 = dot(@29, @58) */
  w63 = casadi_dot(4, w29, w58);
  /* #721: @57 = (@57/@8) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w08;
  /* #722: @65 = (@59*@41) */
  for (i=0, rr=w65, cr=w59; i<4; ++i) (*rr++)  = ((*cr++)*w41);
  /* #723: @57 = (@57-@65) */
  for (i=0, rr=w57, cs=w65; i<4; ++i) (*rr++) -= (*cs++);
  /* #724: @57 = (-@57) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #725: @67 = dot(@57, @39) */
  w67 = casadi_dot(4, w57, w39);
  /* #726: @63 = (@63+@67) */
  w63 += w67;
  /* #727: @63 = (@63/@8) */
  w63 /= w08;
  /* #728: @67 = (@43*@41) */
  w67  = (w43*w41);
  /* #729: @63 = (@63-@67) */
  w63 -= w67;
  /* #730: @57 = (@27*@63) */
  for (i=0, rr=w57, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w63);
  /* #731: @52 = (@42*@52) */
  w52  = (w42*w52);
  /* #732: @65 = dense(@52) */
  casadi_densify((&w52), casadi_s11, w65, 0);
  /* #733: @57 = (@57+@65) */
  for (i=0, rr=w57, cs=w65; i<4; ++i) (*rr++) += (*cs++);
  /* #734: @46 = @21; (@46[6:10] += @57) */
  casadi_copy(w21, 13, w46);
  for (rr=w46+6, cs=w57; rr!=w46+10; rr+=1) *rr += *cs++;
  /* #735: @53 = sparsity_cast(@53) */
  /* #736: @53 = (-@53) */
  w53 = (- w53 );
  /* #737: @53 = @53' */
  /* #738: @75 = mac(@53,@24,@1) */
  casadi_copy(w01, 3, w75);
  casadi_mtimes((&w53), casadi_s12, w24, casadi_s2, w75, casadi_s1, w, 0);
  /* #739: @75 = @75' */
  /* #740: @61 = mac(@53,@47,@1) */
  casadi_copy(w01, 3, w61);
  casadi_mtimes((&w53), casadi_s12, w47, casadi_s2, w61, casadi_s1, w, 0);
  /* #741: @61 = @61' */
  /* #742: @75 = (@75+@61) */
  for (i=0, rr=w75, cs=w61; i<3; ++i) (*rr++) += (*cs++);
  /* #743: @75 = (-@75) */
  for (i=0, rr=w75, cs=w75; i<3; ++i) *rr++ = (- *cs++ );
  /* #744: (@46[:3] += @75) */
  for (rr=w46+0, cs=w75; rr!=w46+3; rr+=1) *rr += *cs++;
  /* #745: {@53, @52, @63, @67, @45, @66, @17, @48, @64, @68, @69, @72, @18} = vertsplit(@46) */
  w53 = w46[0];
  w52 = w46[1];
  w63 = w46[2];
  w67 = w46[3];
  w45 = w46[4];
  w66 = w46[5];
  w17 = w46[6];
  w48 = w46[7];
  w64 = w46[8];
  w68 = w46[9];
  w69 = w46[10];
  w72 = w46[11];
  w18 = w46[12];
  /* #746: @58 = (@58/@8) */
  for (i=0, rr=w58; i<4; ++i) (*rr++) /= w08;
  /* #747: @57 = (@36*@41) */
  for (i=0, rr=w57, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w41);
  /* #748: @58 = (@58-@57) */
  for (i=0, rr=w58, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #749: {@41, @70, @71, @50} = vertsplit(@58) */
  w41 = w58[0];
  w70 = w58[1];
  w71 = w58[2];
  w50 = w58[3];
  /* #750: @41 = (@41+@17) */
  w41 += w17;
  /* #751: @48 = (@48-@70) */
  w48 -= w70;
  /* #752: @64 = (@64-@71) */
  w64 -= w71;
  /* #753: @68 = (@68-@50) */
  w68 -= w50;
  /* #754: @46 = vertcat(@53, @52, @63, @67, @45, @66, @41, @48, @64, @68, @69, @72, @18) */
  rr=w46;
  *rr++ = w53;
  *rr++ = w52;
  *rr++ = w63;
  *rr++ = w67;
  *rr++ = w45;
  *rr++ = w66;
  *rr++ = w41;
  *rr++ = w48;
  *rr++ = w64;
  *rr++ = w68;
  *rr++ = w69;
  *rr++ = w72;
  *rr++ = w18;
  /* #755: @73 = @46[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w73, cs=w46; cii!=casadi_s4+7; ++cii) *rr++ = cs[*cii];
  /* #756: (@54[6, 7, 8, 17, 18, 19, 20] = @73) */
  for (cii=casadi_s13, rr=w54, cs=w73; cii!=casadi_s13+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #757: (@54[2, 5, 8, 11, 15, 19, 23] = @73) */
  for (cii=casadi_s14, rr=w54, cs=w73; cii!=casadi_s14+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #758: @53 = ones(13x1,1nz) */
  w53 = 1.;
  /* #759: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @52, NULL, NULL, NULL} = vertsplit(@53) */
  w52 = w53;
  /* #760: @53 = (-@52) */
  w53 = (- w52 );
  /* #761: @63 = vertcat(@56, @56, @56, @53) */
  rr=(&w63);
  *rr++ = w53;
  /* #762: @63 = (@63/@8) */
  w63 /= w08;
  /* #763: @58 = dense(@63) */
  casadi_densify((&w63), casadi_s15, w58, 0);
  /* #764: @63 = project(@27) */
  casadi_sparsify(w27, (&w63), casadi_s15, 0);
  /* #765: @52 = sparsity_cast(@52) */
  /* #766: @53 = dot(@63, @52) */
  w53 = casadi_dot(1, (&w63), (&w52));
  /* #767: @53 = (@53/@8) */
  w53 /= w08;
  /* #768: @26 = (@26*@53) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) *= w53;
  /* #769: @58 = (@58-@26) */
  for (i=0, rr=w58, cs=w26; i<4; ++i) (*rr++) -= (*cs++);
  /* #770: {@63, @67, @45, @66} = vertsplit(@58) */
  w63 = w58[0];
  w67 = w58[1];
  w45 = w58[2];
  w66 = w58[3];
  /* #771: @41 = (@4*@63) */
  w41  = (w04*w63);
  /* #772: @48 = (@5*@67) */
  w48  = (w05*w67);
  /* #773: @41 = (@41-@48) */
  w41 -= w48;
  /* #774: @48 = (@6*@45) */
  w48  = (w06*w45);
  /* #775: @41 = (@41-@48) */
  w41 -= w48;
  /* #776: @48 = (@7*@66) */
  w48  = (w07*w66);
  /* #777: @41 = (@41-@48) */
  w41 -= w48;
  /* #778: @48 = (@5*@63) */
  w48  = (w05*w63);
  /* #779: @64 = (@4*@67) */
  w64  = (w04*w67);
  /* #780: @48 = (@48+@64) */
  w48 += w64;
  /* #781: @64 = (@7*@45) */
  w64  = (w07*w45);
  /* #782: @48 = (@48+@64) */
  w48 += w64;
  /* #783: @64 = (@6*@66) */
  w64  = (w06*w66);
  /* #784: @48 = (@48-@64) */
  w48 -= w64;
  /* #785: @64 = (@6*@63) */
  w64  = (w06*w63);
  /* #786: @68 = (@7*@67) */
  w68  = (w07*w67);
  /* #787: @64 = (@64-@68) */
  w64 -= w68;
  /* #788: @68 = (@4*@45) */
  w68  = (w04*w45);
  /* #789: @64 = (@64+@68) */
  w64 += w68;
  /* #790: @68 = (@5*@66) */
  w68  = (w05*w66);
  /* #791: @64 = (@64+@68) */
  w64 += w68;
  /* #792: @63 = (@7*@63) */
  w63  = (w07*w63);
  /* #793: @67 = (@6*@67) */
  w67  = (w06*w67);
  /* #794: @63 = (@63+@67) */
  w63 += w67;
  /* #795: @45 = (@5*@45) */
  w45  = (w05*w45);
  /* #796: @63 = (@63-@45) */
  w63 -= w45;
  /* #797: @66 = (@4*@66) */
  w66  = (w04*w66);
  /* #798: @63 = (@63+@66) */
  w63 += w66;
  /* #799: @26 = vertcat(@41, @48, @64, @63) */
  rr=w26;
  *rr++ = w41;
  *rr++ = w48;
  *rr++ = w64;
  *rr++ = w63;
  /* #800: @57 = (-@26) */
  for (i=0, rr=w57, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #801: @57 = (@13?@57:0) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #802: @26 = (@12?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #803: @57 = (@57+@26) */
  for (i=0, rr=w57, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #804: @75 = @57[1:4] */
  for (rr=w75, cs=w57+1; cs!=w57+4; cs+=1) *rr++ = *cs;
  /* #805: @41 = dot(@20, @75) */
  w41 = casadi_dot(3, w20, w75);
  /* #806: @41 = (@41/@14) */
  w41 /= w14;
  /* #807: @48 = (@41/@2) */
  w48  = (w41/w02);
  /* #808: @51 = (@51*@41) */
  w51 *= w41;
  /* #809: @64 = @57[0] */
  for (rr=(&w64), cs=w57+0; cs!=w57+1; cs+=1) *rr++ = *cs;
  /* #810: @15 = (@15*@64) */
  w15 *= w64;
  /* #811: @51 = (@51+@15) */
  w51 += w15;
  /* #812: @40 = (@40*@51) */
  w40 *= w51;
  /* #813: @48 = (@48-@40) */
  w48 -= w40;
  /* #814: @48 = (@11*@48) */
  w48  = (w11*w48);
  /* #815: @61 = (2.*@75) */
  for (i=0, rr=w61, cs=w75; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #816: @37 = (@9*@61) */
  for (i=0, rr=w37, cs=w61; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #817: @40 = (@16*@41) */
  w40  = (w16*w41);
  /* #818: @15 = (@0*@64) */
  w15  = (w00*w64);
  /* #819: @40 = (@40-@15) */
  w40 -= w15;
  /* #820: @25 = (@30*@40) */
  for (i=0, rr=w25, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w40);
  /* #821: @37 = (@37+@25) */
  for (i=0, rr=w37, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #822: @37 = (@37/@3) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) /= w03;
  /* #823: @31 = (@31*@41) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) *= w41;
  /* #824: @37 = (@37-@31) */
  for (i=0, rr=w37, cs=w31; i<3; ++i) (*rr++) -= (*cs++);
  /* #825: @31 = @37' */
  casadi_copy(w37, 3, w31);
  /* #826: @25 = mac(@31,@23,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w31+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #827: @25 = @25' */
  /* #828: @1 = mac(@31,@34,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w31+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #829: @1 = @1' */
  /* #830: @25 = (@25+@1) */
  for (i=0, rr=w25, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #831: @1 = (@25/@3) */
  for (i=0, rr=w01, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #832: @38 = (@38*@41) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) *= w41;
  /* #833: @1 = (@1-@38) */
  for (i=0, rr=w01, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #834: @15 = dot(@30, @1) */
  w15 = casadi_dot(3, w30, w01);
  /* #835: @63 = dot(@61, @35) */
  w63 = casadi_dot(3, w61, w35);
  /* #836: @15 = (@15+@63) */
  w15 += w63;
  /* #837: @0 = (@0*@15) */
  w00 *= w15;
  /* #838: @48 = (@48+@0) */
  w48 += w00;
  /* #839: @48 = (-@48) */
  w48 = (- w48 );
  /* #840: (@28[0] += @48) */
  for (rr=w28+0, cs=(&w48); rr!=w28+1; rr+=1) *rr += *cs++;
  /* #841: @48 = dot(@32, @25) */
  w48 = casadi_dot(3, w32, w25);
  /* #842: @37 = (@37/@3) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) /= w03;
  /* #843: @60 = (@60*@41) */
  for (i=0, rr=w60; i<3; ++i) (*rr++) *= w41;
  /* #844: @37 = (@37-@60) */
  for (i=0, rr=w37, cs=w60; i<3; ++i) (*rr++) -= (*cs++);
  /* #845: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (- *cs++ );
  /* #846: @3 = dot(@37, @33) */
  w03 = casadi_dot(3, w37, w33);
  /* #847: @48 = (@48+@3) */
  w48 += w03;
  /* #848: @64 = (@64/@2) */
  w64 /= w02;
  /* #849: @44 = (@44*@51) */
  w44 *= w51;
  /* #850: @64 = (@64-@44) */
  w64 -= w44;
  /* #851: @11 = (@11*@64) */
  w11 *= w64;
  /* #852: @16 = (@16*@15) */
  w16 *= w15;
  /* #853: @11 = (@11+@16) */
  w11 += w16;
  /* #854: @48 = (@48+@11) */
  w48 += w11;
  /* #855: @48 = (@48/@14) */
  w48 /= w14;
  /* #856: @49 = (@49*@41) */
  w49 *= w41;
  /* #857: @48 = (@48-@49) */
  w48 -= w49;
  /* #858: @20 = (@20*@48) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w48;
  /* #859: @75 = (@10*@75) */
  for (i=0, rr=w75, cs=w75; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #860: @20 = (@20+@75) */
  for (i=0, rr=w20, cs=w75; i<3; ++i) (*rr++) += (*cs++);
  /* #861: @35 = (@35*@40) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) *= w40;
  /* #862: @1 = (@9*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #863: @35 = (@35+@1) */
  for (i=0, rr=w35, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #864: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #865: @20 = (@20+@35) */
  for (i=0, rr=w20, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #866: (@28[1:4] += @20) */
  for (rr=w28+1, cs=w20; rr!=w28+4; rr+=1) *rr += *cs++;
  /* #867: @57 = (@12?@28:0) */
  for (i=0, rr=w57, cs=w28; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #868: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #869: @28 = (@13?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #870: @57 = (@57+@28) */
  for (i=0, rr=w57, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #871: {@13, @12, @9, @40} = vertsplit(@57) */
  w13 = w57[0];
  w12 = w57[1];
  w09 = w57[2];
  w40 = w57[3];
  /* #872: @10 = (@7*@40) */
  w10  = (w07*w40);
  /* #873: @48 = (@6*@9) */
  w48  = (w06*w09);
  /* #874: @10 = (@10+@48) */
  w10 += w48;
  /* #875: @48 = (@5*@12) */
  w48  = (w05*w12);
  /* #876: @10 = (@10+@48) */
  w10 += w48;
  /* #877: @48 = (@4*@13) */
  w48  = (w04*w13);
  /* #878: @10 = (@10+@48) */
  w10 += w48;
  /* #879: @48 = (@6*@40) */
  w48  = (w06*w40);
  /* #880: @49 = (@7*@9) */
  w49  = (w07*w09);
  /* #881: @48 = (@48-@49) */
  w48 -= w49;
  /* #882: @49 = (@4*@12) */
  w49  = (w04*w12);
  /* #883: @48 = (@48+@49) */
  w48 += w49;
  /* #884: @49 = (@5*@13) */
  w49  = (w05*w13);
  /* #885: @48 = (@48-@49) */
  w48 -= w49;
  /* #886: @49 = (@4*@9) */
  w49  = (w04*w09);
  /* #887: @41 = (@5*@40) */
  w41  = (w05*w40);
  /* #888: @49 = (@49-@41) */
  w49 -= w41;
  /* #889: @41 = (@7*@12) */
  w41  = (w07*w12);
  /* #890: @49 = (@49+@41) */
  w49 += w41;
  /* #891: @41 = (@6*@13) */
  w41  = (w06*w13);
  /* #892: @49 = (@49-@41) */
  w49 -= w41;
  /* #893: @4 = (@4*@40) */
  w04 *= w40;
  /* #894: @5 = (@5*@9) */
  w05 *= w09;
  /* #895: @4 = (@4+@5) */
  w04 += w05;
  /* #896: @6 = (@6*@12) */
  w06 *= w12;
  /* #897: @4 = (@4-@6) */
  w04 -= w06;
  /* #898: @7 = (@7*@13) */
  w07 *= w13;
  /* #899: @4 = (@4-@7) */
  w04 -= w07;
  /* #900: @57 = vertcat(@10, @48, @49, @4) */
  rr=w57;
  *rr++ = w10;
  *rr++ = w48;
  *rr++ = w49;
  *rr++ = w04;
  /* #901: @10 = dot(@29, @57) */
  w10 = casadi_dot(4, w29, w57);
  /* #902: @58 = (@58/@8) */
  for (i=0, rr=w58; i<4; ++i) (*rr++) /= w08;
  /* #903: @59 = (@59*@53) */
  for (i=0, rr=w59; i<4; ++i) (*rr++) *= w53;
  /* #904: @58 = (@58-@59) */
  for (i=0, rr=w58, cs=w59; i<4; ++i) (*rr++) -= (*cs++);
  /* #905: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) *rr++ = (- *cs++ );
  /* #906: @48 = dot(@58, @39) */
  w48 = casadi_dot(4, w58, w39);
  /* #907: @10 = (@10+@48) */
  w10 += w48;
  /* #908: @10 = (@10/@8) */
  w10 /= w08;
  /* #909: @43 = (@43*@53) */
  w43 *= w53;
  /* #910: @10 = (@10-@43) */
  w10 -= w43;
  /* #911: @27 = (@27*@10) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) *= w10;
  /* #912: @42 = (@42*@52) */
  w42 *= w52;
  /* #913: @58 = dense(@42) */
  casadi_densify((&w42), casadi_s15, w58, 0);
  /* #914: @27 = (@27+@58) */
  for (i=0, rr=w27, cs=w58; i<4; ++i) (*rr++) += (*cs++);
  /* #915: (@21[6:10] += @27) */
  for (rr=w21+6, cs=w27; rr!=w21+10; rr+=1) *rr += *cs++;
  /* #916: {@42, @52, @10, @43, @48, @49, @4, @7, @13, @6, @12, @5, @9} = vertsplit(@21) */
  w42 = w21[0];
  w52 = w21[1];
  w10 = w21[2];
  w43 = w21[3];
  w48 = w21[4];
  w49 = w21[5];
  w04 = w21[6];
  w07 = w21[7];
  w13 = w21[8];
  w06 = w21[9];
  w12 = w21[10];
  w05 = w21[11];
  w09 = w21[12];
  /* #917: @57 = (@57/@8) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w08;
  /* #918: @36 = (@36*@53) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) *= w53;
  /* #919: @57 = (@57-@36) */
  for (i=0, rr=w57, cs=w36; i<4; ++i) (*rr++) -= (*cs++);
  /* #920: {@53, @8, @40, @41} = vertsplit(@57) */
  w53 = w57[0];
  w08 = w57[1];
  w40 = w57[2];
  w41 = w57[3];
  /* #921: @53 = (@53+@4) */
  w53 += w04;
  /* #922: @7 = (@7-@8) */
  w07 -= w08;
  /* #923: @13 = (@13-@40) */
  w13 -= w40;
  /* #924: @6 = (@6-@41) */
  w06 -= w41;
  /* #925: @21 = vertcat(@42, @52, @10, @43, @48, @49, @53, @7, @13, @6, @12, @5, @9) */
  rr=w21;
  *rr++ = w42;
  *rr++ = w52;
  *rr++ = w10;
  *rr++ = w43;
  *rr++ = w48;
  *rr++ = w49;
  *rr++ = w53;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w05;
  *rr++ = w09;
  /* #926: @57 = @21[6:10] */
  for (rr=w57, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #927: (@54[21:25] = @57) */
  for (rr=w54+21, cs=w57; rr!=w54+25; rr+=1) *rr = *cs++;
  /* #928: (@54[12:28:4] = @57) */
  for (rr=w54+12, cs=w57; rr!=w54+28; rr+=4) *rr = *cs++;
  /* #929: @76 = @54' */
  casadi_trans(w54,casadi_s16, w76, casadi_s16, iw);
  /* #930: output[2][0] = @76 */
  casadi_copy(w76, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s18;
    case 2: return casadi_s18;
    case 3: return casadi_s19;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s20;
    case 1: return casadi_s17;
    case 2: return casadi_s16;
    case 3: return casadi_s21;
    case 4: return casadi_s22;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 271;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 18*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 271*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
