/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {1, 4, 0, 1, 2, 3, 4, 0,
  0, 0, 0};
static const casadi_int casadi_s1[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s4[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s5[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s7[11] = 
  {0, 1, 2, 3, 4, 5, 6, 10,
  11, 12, 13};
static const casadi_int casadi_s8[11] = 
  {0, 1, 2, 3, 16, 17, 18, 25,
  26, 27, 28};
static const casadi_int casadi_s9[11] = 
  {0, 4, 8, 12, 16, 19, 22, 25,
  29, 33, 37};
static const casadi_int casadi_s10[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s12[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[11] = 
  {4, 5, 6, 7, 19, 20, 21, 29,
  30, 31, 32};
static const casadi_int casadi_s14[11] = 
  {1, 5, 9, 13, 17, 20, 23, 26,
  30, 34, 38};
static const casadi_int casadi_s15[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s16[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s17[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s18[11] = 
  {8, 9, 10, 11, 22, 23, 24, 33,
  34, 35, 36};
static const casadi_int casadi_s19[11] = 
  {2, 6, 10, 14, 18, 21, 24, 27,
  31, 35, 39};
static const casadi_int casadi_s20[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s21[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s22[61] = 
  {17, 17, 0, 4, 8, 12, 16, 19,
  22, 25, 25, 25, 25, 29, 33, 37,
  41, 41, 41, 41, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 4, 5, 6, 4,
  5, 6, 4, 5, 6, 10, 11, 12,
  13, 10, 11, 12, 13, 10, 11, 12,
  13, 10, 11, 12, 13};
static const casadi_int casadi_s23[3] = {13, 1, 1};
static const casadi_int casadi_s24[3] = {4, 1, 1};
static const casadi_int casadi_s25[3] = {0, 1, 1};
static const casadi_int casadi_s26[3] = {17, 1, 1};
static const casadi_int casadi_s27[3] = {1, 1, 1};
static const casadi_int casadi_s28[3] = {0, 0, 1};
static const casadi_int casadi_s29[3] = {0, 17, 1};

/* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess:(i0[13],i1[4],i2[0],i3[17])->(o0,o1[17],o2[17x17,41nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *tt, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42;
  casadi_real *w22=w+55, *w23=w+58, *w24=w+67, *w25=w+76, *w26=w+79, *w27=w+83, *w28=w+87, *w29=w+91, *w30=w+107, *w31=w+111, *w32=w+115, *w33=w+119;
  casadi_real *w34=w+123, *w35=w+126, *w36=w+129, *w37=w+132, *w38=w+135, *w39=w+151, *w40=w+160, *w41=w+163, *w42=w+166, w43, w44, w45;
  casadi_real w46, w47, w48, *w49=w+175, *w50=w+188, w51, w52, w53, w54, w55, w56, *w57=w+203;
  casadi_real *w58=w+244, *w60=w+253, *w61=w+257, w62, w63, *w64=w+263, *w65=w+267, *w66=w+270, *w67=w+273, w68, w69, w70;
  casadi_real w71, *w72=w+280, w73, w74, w75, w76, w77, w78, w79, *w80=w+291, *w81=w+302, *w82=w+305;
  casadi_real *w83=w+307, *w84=w+315;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 25 */
  w02 = 25.;
  /* #40: @24 = @23; (@24[0] = @2) */
  casadi_copy(w23, 9, w24);
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #41: (@24[4] = @2) */
  for (rr=w24+4, cs=(&w02); rr!=w24+5; rr+=1) *rr = *cs++;
  /* #42: @2 = 30 */
  w02 = 30.;
  /* #43: (@24[8] = @2) */
  for (rr=w24+8, cs=(&w02); rr!=w24+9; rr+=1) *rr = *cs++;
  /* #44: @25 = mac(@22,@24,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #45: @2 = mac(@25,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #46: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #47: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #48: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #49: @5 = input[1][2] */
  w05 = arg[1] ? arg[1][2] : 0;
  /* #50: @6 = input[1][3] */
  w06 = arg[1] ? arg[1][3] : 0;
  /* #51: @27 = vertcat(@3, @4, @5, @6) */
  rr=w27;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  /* #52: @28 = @27' */
  casadi_copy(w27, 4, w28);
  /* #53: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #54: @3 = 1 */
  w03 = 1.;
  /* #55: (@29[0] = @3) */
  for (rr=w29+0, cs=(&w03); rr!=w29+1; rr+=1) *rr = *cs++;
  /* #56: @3 = 800 */
  w03 = 800.;
  /* #57: (@29[5] = @3) */
  for (rr=w29+5, cs=(&w03); rr!=w29+6; rr+=1) *rr = *cs++;
  /* #58: (@29[10] = @3) */
  for (rr=w29+10, cs=(&w03); rr!=w29+11; rr+=1) *rr = *cs++;
  /* #59: (@29[15] = @3) */
  for (rr=w29+15, cs=(&w03); rr!=w29+16; rr+=1) *rr = *cs++;
  /* #60: @30 = mac(@28,@29,@26) */
  casadi_copy(w26, 4, w30);
  for (i=0, rr=w30; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w29+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #61: @3 = mac(@30,@27,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w30+j, ct=w27+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #62: @2 = (@2+@3) */
  w02 += w03;
  /* #63: @9 = (-@9) */
  w09 = (- w09 );
  /* #64: @10 = (-@10) */
  w10 = (- w10 );
  /* #65: @11 = (-@11) */
  w11 = (- w11 );
  /* #66: @27 = vertcat(@8, @9, @10, @11) */
  rr=w27;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #67: @31 = @21[6:10] */
  for (rr=w31, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #68: @8 = ||@31||_F */
  w08 = casadi_norm_2(4, w31);
  /* #69: @27 = (@27/@8) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w08;
  /* #70: {@9, @10, @11, @3} = vertsplit(@27) */
  w09 = w27[0];
  w10 = w27[1];
  w11 = w27[2];
  w03 = w27[3];
  /* #71: @32 = @19[6:10] */
  for (rr=w32, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #72: {@4, @5, @6, @7} = vertsplit(@32) */
  w04 = w32[0];
  w05 = w32[1];
  w06 = w32[2];
  w07 = w32[3];
  /* #73: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #74: @13 = (@10*@5) */
  w13  = (w10*w05);
  /* #75: @12 = (@12-@13) */
  w12 -= w13;
  /* #76: @13 = (@11*@6) */
  w13  = (w11*w06);
  /* #77: @12 = (@12-@13) */
  w12 -= w13;
  /* #78: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #79: @12 = (@12-@13) */
  w12 -= w13;
  /* #80: @13 = (@12<@0) */
  w13  = (w12<w00);
  /* #81: @14 = (@9*@5) */
  w14  = (w09*w05);
  /* #82: @15 = (@10*@4) */
  w15  = (w10*w04);
  /* #83: @14 = (@14+@15) */
  w14 += w15;
  /* #84: @15 = (@11*@7) */
  w15  = (w11*w07);
  /* #85: @14 = (@14+@15) */
  w14 += w15;
  /* #86: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #87: @14 = (@14-@15) */
  w14 -= w15;
  /* #88: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #89: @16 = (@10*@7) */
  w16  = (w10*w07);
  /* #90: @15 = (@15-@16) */
  w15 -= w16;
  /* #91: @16 = (@11*@4) */
  w16  = (w11*w04);
  /* #92: @15 = (@15+@16) */
  w15 += w16;
  /* #93: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #94: @15 = (@15+@16) */
  w15 += w16;
  /* #95: @9 = (@9*@7) */
  w09 *= w07;
  /* #96: @10 = (@10*@6) */
  w10 *= w06;
  /* #97: @9 = (@9+@10) */
  w09 += w10;
  /* #98: @11 = (@11*@5) */
  w11 *= w05;
  /* #99: @9 = (@9-@11) */
  w09 -= w11;
  /* #100: @3 = (@3*@4) */
  w03 *= w04;
  /* #101: @9 = (@9+@3) */
  w09 += w03;
  /* #102: @32 = vertcat(@12, @14, @15, @9) */
  rr=w32;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  /* #103: @33 = (-@32) */
  for (i=0, rr=w33, cs=w32; i<4; ++i) *rr++ = (- *cs++ );
  /* #104: @33 = (@13?@33:0) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #105: @12 = (!@13) */
  w12 = (! w13 );
  /* #106: @32 = (@12?@32:0) */
  for (i=0, rr=w32, cs=w32; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #107: @33 = (@33+@32) */
  for (i=0, rr=w33, cs=w32; i<4; ++i) (*rr++) += (*cs++);
  /* #108: @20 = @33[1:4] */
  for (rr=w20, cs=w33+1; cs!=w33+4; cs+=1) *rr++ = *cs;
  /* #109: @34 = (2.*@20) */
  for (i=0, rr=w34, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #110: @14 = ||@20||_F */
  w14 = casadi_norm_2(3, w20);
  /* #111: @15 = @33[0] */
  for (rr=(&w15), cs=w33+0; cs!=w33+1; cs+=1) *rr++ = *cs;
  /* #112: @9 = atan2(@14,@15) */
  w09  = atan2(w14,w15);
  /* #113: @35 = (@34*@9) */
  for (i=0, rr=w35, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w09);
  /* #114: @3 = 1e-09 */
  w03 = 1.0000000000000001e-09;
  /* #115: @3 = (@3+@14) */
  w03 += w14;
  /* #116: @35 = (@35/@3) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w03;
  /* #117: @36 = @35' */
  casadi_copy(w35, 3, w36);
  /* #118: @11 = 12 */
  w11 = 12.;
  /* #119: (@23[0] = @11) */
  for (rr=w23+0, cs=(&w11); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #120: (@23[4] = @11) */
  for (rr=w23+4, cs=(&w11); rr!=w23+5; rr+=1) *rr = *cs++;
  /* #121: (@23[8] = @11) */
  for (rr=w23+8, cs=(&w11); rr!=w23+9; rr+=1) *rr = *cs++;
  /* #122: @37 = mac(@36,@23,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #123: @0 = mac(@37,@35,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #124: @2 = (@2+@0) */
  w02 += w00;
  /* #125: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #126: @30 = @30' */
  /* #127: @38 = @29' */
  for (i=0, rr=w38, cs=w29; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #128: @33 = mac(@28,@38,@26) */
  casadi_copy(w26, 4, w33);
  for (i=0, rr=w33; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w38+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #129: @33 = @33' */
  /* #130: @30 = (@30+@33) */
  for (i=0, rr=w30, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #131: {@2, @0, @11, @10} = vertsplit(@30) */
  w02 = w30[0];
  w00 = w30[1];
  w11 = w30[2];
  w10 = w30[3];
  /* #132: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #133: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #134: output[1][2] = @11 */
  if (res[1]) res[1][2] = w11;
  /* #135: output[1][3] = @10 */
  if (res[1]) res[1][3] = w10;
  /* #136: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #137: @27 = (@27/@8) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w08;
  /* #138: @30 = (-@27) */
  for (i=0, rr=w30, cs=w27; i<4; ++i) *rr++ = (- *cs++ );
  /* #139: @33 = zeros(4x1) */
  casadi_clear(w33, 4);
  /* #140: @10 = sq(@14) */
  w10 = casadi_sq( w14 );
  /* #141: @11 = sq(@15) */
  w11 = casadi_sq( w15 );
  /* #142: @10 = (@10+@11) */
  w10 += w11;
  /* #143: @11 = (@14/@10) */
  w11  = (w14/w10);
  /* #144: @37 = @37' */
  /* #145: @39 = @23' */
  for (i=0, rr=w39, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #146: @40 = mac(@36,@39,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #147: @40 = @40' */
  /* #148: @37 = (@37+@40) */
  for (i=0, rr=w37, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #149: @40 = (@37/@3) */
  for (i=0, rr=w40, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #150: @0 = dot(@34, @40) */
  w00 = casadi_dot(3, w34, w40);
  /* #151: @2 = (@11*@0) */
  w02  = (w11*w00);
  /* #152: @2 = (-@2) */
  w02 = (- w02 );
  /* #153: @28 = @33; (@28[0] += @2) */
  casadi_copy(w33, 4, w28);
  for (rr=w28+0, cs=(&w02); rr!=w28+1; rr+=1) *rr += *cs++;
  /* #154: @35 = (@35/@3) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w03;
  /* #155: @36 = (-@35) */
  for (i=0, rr=w36, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #156: @2 = dot(@36, @37) */
  w02 = casadi_dot(3, w36, w37);
  /* #157: @16 = (@15/@10) */
  w16  = (w15/w10);
  /* #158: @17 = (@16*@0) */
  w17  = (w16*w00);
  /* #159: @2 = (@2+@17) */
  w02 += w17;
  /* #160: @2 = (@2/@14) */
  w02 /= w14;
  /* #161: @41 = (@2*@20) */
  for (i=0, rr=w41, cs=w20; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #162: @42 = (@9*@40) */
  for (i=0, rr=w42, cs=w40; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #163: @42 = (2.*@42) */
  for (i=0, rr=w42, cs=w42; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #164: @41 = (@41+@42) */
  for (i=0, rr=w41, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #165: (@28[1:4] += @41) */
  for (rr=w28+1, cs=w41; rr!=w28+4; rr+=1) *rr += *cs++;
  /* #166: @32 = (@12?@28:0) */
  for (i=0, rr=w32, cs=w28; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #167: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #168: @28 = (@13?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #169: @32 = (@32+@28) */
  for (i=0, rr=w32, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #170: {@17, @18, @43, @44} = vertsplit(@32) */
  w17 = w32[0];
  w18 = w32[1];
  w43 = w32[2];
  w44 = w32[3];
  /* #171: @45 = (@7*@44) */
  w45  = (w07*w44);
  /* #172: @46 = (@6*@43) */
  w46  = (w06*w43);
  /* #173: @45 = (@45+@46) */
  w45 += w46;
  /* #174: @46 = (@5*@18) */
  w46  = (w05*w18);
  /* #175: @45 = (@45+@46) */
  w45 += w46;
  /* #176: @46 = (@4*@17) */
  w46  = (w04*w17);
  /* #177: @45 = (@45+@46) */
  w45 += w46;
  /* #178: @46 = (@6*@44) */
  w46  = (w06*w44);
  /* #179: @47 = (@7*@43) */
  w47  = (w07*w43);
  /* #180: @46 = (@46-@47) */
  w46 -= w47;
  /* #181: @47 = (@4*@18) */
  w47  = (w04*w18);
  /* #182: @46 = (@46+@47) */
  w46 += w47;
  /* #183: @47 = (@5*@17) */
  w47  = (w05*w17);
  /* #184: @46 = (@46-@47) */
  w46 -= w47;
  /* #185: @47 = (@4*@43) */
  w47  = (w04*w43);
  /* #186: @48 = (@5*@44) */
  w48  = (w05*w44);
  /* #187: @47 = (@47-@48) */
  w47 -= w48;
  /* #188: @48 = (@7*@18) */
  w48  = (w07*w18);
  /* #189: @47 = (@47+@48) */
  w47 += w48;
  /* #190: @48 = (@6*@17) */
  w48  = (w06*w17);
  /* #191: @47 = (@47-@48) */
  w47 -= w48;
  /* #192: @44 = (@4*@44) */
  w44  = (w04*w44);
  /* #193: @43 = (@5*@43) */
  w43  = (w05*w43);
  /* #194: @44 = (@44+@43) */
  w44 += w43;
  /* #195: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #196: @44 = (@44-@18) */
  w44 -= w18;
  /* #197: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #198: @44 = (@44-@17) */
  w44 -= w17;
  /* #199: @32 = vertcat(@45, @46, @47, @44) */
  rr=w32;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w44;
  /* #200: @45 = dot(@30, @32) */
  w45 = casadi_dot(4, w30, w32);
  /* #201: @45 = (@45/@8) */
  w45 /= w08;
  /* #202: @28 = (@45*@31) */
  for (i=0, rr=w28, cs=w31; i<4; ++i) (*rr++)  = (w45*(*cs++));
  /* #203: @49 = @21; (@49[6:10] += @28) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w28; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #204: @25 = @25' */
  /* #205: @50 = @24' */
  for (i=0, rr=w50, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #206: @41 = mac(@22,@50,@1) */
  casadi_copy(w01, 3, w41);
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w50+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #207: @41 = @41' */
  /* #208: @25 = (@25+@41) */
  for (i=0, rr=w25, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #209: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (- *cs++ );
  /* #210: (@49[:3] += @25) */
  for (rr=w49+0, cs=w25; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #211: {@46, @47, @44, @17, @18, @43, @48, @51, @52, @53, @54, @55, @56} = vertsplit(@49) */
  w46 = w49[0];
  w47 = w49[1];
  w44 = w49[2];
  w17 = w49[3];
  w18 = w49[4];
  w43 = w49[5];
  w48 = w49[6];
  w51 = w49[7];
  w52 = w49[8];
  w53 = w49[9];
  w54 = w49[10];
  w55 = w49[11];
  w56 = w49[12];
  /* #212: output[1][4] = @46 */
  if (res[1]) res[1][4] = w46;
  /* #213: output[1][5] = @47 */
  if (res[1]) res[1][5] = w47;
  /* #214: output[1][6] = @44 */
  if (res[1]) res[1][6] = w44;
  /* #215: output[1][7] = @17 */
  if (res[1]) res[1][7] = w17;
  /* #216: output[1][8] = @18 */
  if (res[1]) res[1][8] = w18;
  /* #217: output[1][9] = @43 */
  if (res[1]) res[1][9] = w43;
  /* #218: @28 = (@32/@8) */
  for (i=0, rr=w28, cr=w32; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #219: {@43, @18, @17, @44} = vertsplit(@28) */
  w43 = w28[0];
  w18 = w28[1];
  w17 = w28[2];
  w44 = w28[3];
  /* #220: @43 = (@43+@48) */
  w43 += w48;
  /* #221: output[1][10] = @43 */
  if (res[1]) res[1][10] = w43;
  /* #222: @51 = (@51-@18) */
  w51 -= w18;
  /* #223: output[1][11] = @51 */
  if (res[1]) res[1][11] = w51;
  /* #224: @52 = (@52-@17) */
  w52 -= w17;
  /* #225: output[1][12] = @52 */
  if (res[1]) res[1][12] = w52;
  /* #226: @53 = (@53-@44) */
  w53 -= w44;
  /* #227: output[1][13] = @53 */
  if (res[1]) res[1][13] = w53;
  /* #228: output[1][14] = @54 */
  if (res[1]) res[1][14] = w54;
  /* #229: output[1][15] = @55 */
  if (res[1]) res[1][15] = w55;
  /* #230: output[1][16] = @56 */
  if (res[1]) res[1][16] = w56;
  /* #231: @57 = zeros(17x17,41nz) */
  casadi_clear(w57, 41);
  /* #232: @58 = ones(17x1,9nz) */
  casadi_fill(w58, 9, 1.);
  /* #233: {@56, NULL, NULL, NULL, @55, NULL, NULL, NULL, NULL, NULL, @54, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@58) */
  w56 = w58[0];
  w55 = w58[1];
  w54 = w58[5];
  /* #234: @59 = 00 */
  /* #235: @53 = vertcat(@56, @59, @59, @59) */
  rr=(&w53);
  *rr++ = w56;
  /* #236: @53 = @53' */
  /* #237: @60 = mac(@53,@29,@26) */
  casadi_copy(w26, 4, w60);
  casadi_mtimes((&w53), casadi_s2, w29, casadi_s1, w60, casadi_s0, w, 0);
  /* #238: @60 = @60' */
  /* #239: @61 = mac(@53,@38,@26) */
  casadi_copy(w26, 4, w61);
  casadi_mtimes((&w53), casadi_s2, w38, casadi_s1, w61, casadi_s0, w, 0);
  /* #240: @61 = @61' */
  /* #241: @60 = (@60+@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #242: {@53, @56, @44, @52} = vertsplit(@60) */
  w53 = w60[0];
  w56 = w60[1];
  w44 = w60[2];
  w52 = w60[3];
  /* #243: @17 = vertcat(@54, @59, @59, @59) */
  rr=(&w17);
  *rr++ = w54;
  /* #244: @17 = (@17/@8) */
  w17 /= w08;
  /* #245: @60 = dense(@17) */
  casadi_densify((&w17), casadi_s3, w60, 0);
  /* #246: @17 = project(@31) */
  casadi_sparsify(w31, (&w17), casadi_s3, 0);
  /* #247: @54 = sparsity_cast(@54) */
  /* #248: @51 = dot(@17, @54) */
  w51 = casadi_dot(1, (&w17), (&w54));
  /* #249: @51 = (@51/@8) */
  w51 /= w08;
  /* #250: @61 = (@27*@51) */
  for (i=0, rr=w61, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w51);
  /* #251: @60 = (@60-@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #252: {@17, @18, @43, @48} = vertsplit(@60) */
  w17 = w60[0];
  w18 = w60[1];
  w43 = w60[2];
  w48 = w60[3];
  /* #253: @47 = (@4*@17) */
  w47  = (w04*w17);
  /* #254: @46 = (@5*@18) */
  w46  = (w05*w18);
  /* #255: @47 = (@47-@46) */
  w47 -= w46;
  /* #256: @46 = (@6*@43) */
  w46  = (w06*w43);
  /* #257: @47 = (@47-@46) */
  w47 -= w46;
  /* #258: @46 = (@7*@48) */
  w46  = (w07*w48);
  /* #259: @47 = (@47-@46) */
  w47 -= w46;
  /* #260: @46 = (@5*@17) */
  w46  = (w05*w17);
  /* #261: @62 = (@4*@18) */
  w62  = (w04*w18);
  /* #262: @46 = (@46+@62) */
  w46 += w62;
  /* #263: @62 = (@7*@43) */
  w62  = (w07*w43);
  /* #264: @46 = (@46+@62) */
  w46 += w62;
  /* #265: @62 = (@6*@48) */
  w62  = (w06*w48);
  /* #266: @46 = (@46-@62) */
  w46 -= w62;
  /* #267: @62 = (@6*@17) */
  w62  = (w06*w17);
  /* #268: @63 = (@7*@18) */
  w63  = (w07*w18);
  /* #269: @62 = (@62-@63) */
  w62 -= w63;
  /* #270: @63 = (@4*@43) */
  w63  = (w04*w43);
  /* #271: @62 = (@62+@63) */
  w62 += w63;
  /* #272: @63 = (@5*@48) */
  w63  = (w05*w48);
  /* #273: @62 = (@62+@63) */
  w62 += w63;
  /* #274: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #275: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #276: @17 = (@17+@18) */
  w17 += w18;
  /* #277: @43 = (@5*@43) */
  w43  = (w05*w43);
  /* #278: @17 = (@17-@43) */
  w17 -= w43;
  /* #279: @48 = (@4*@48) */
  w48  = (w04*w48);
  /* #280: @17 = (@17+@48) */
  w17 += w48;
  /* #281: @61 = vertcat(@47, @46, @62, @17) */
  rr=w61;
  *rr++ = w47;
  *rr++ = w46;
  *rr++ = w62;
  *rr++ = w17;
  /* #282: @64 = (-@61) */
  for (i=0, rr=w64, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #283: @64 = (@13?@64:0) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #284: @61 = (@12?@61:0) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #285: @64 = (@64+@61) */
  for (i=0, rr=w64, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #286: @25 = @64[1:4] */
  for (rr=w25, cs=w64+1; cs!=w64+4; cs+=1) *rr++ = *cs;
  /* #287: @47 = dot(@20, @25) */
  w47 = casadi_dot(3, w20, w25);
  /* #288: @47 = (@47/@14) */
  w47 /= w14;
  /* #289: @46 = (@47/@10) */
  w46  = (w47/w10);
  /* #290: @62 = (@11/@10) */
  w62  = (w11/w10);
  /* #291: @17 = (2.*@14) */
  w17 = (2.* w14 );
  /* #292: @48 = (@17*@47) */
  w48  = (w17*w47);
  /* #293: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #294: @43 = @64[0] */
  for (rr=(&w43), cs=w64+0; cs!=w64+1; cs+=1) *rr++ = *cs;
  /* #295: @18 = (@15*@43) */
  w18  = (w15*w43);
  /* #296: @48 = (@48+@18) */
  w48 += w18;
  /* #297: @18 = (@62*@48) */
  w18  = (w62*w48);
  /* #298: @46 = (@46-@18) */
  w46 -= w18;
  /* #299: @46 = (@0*@46) */
  w46  = (w00*w46);
  /* #300: @41 = (2.*@25) */
  for (i=0, rr=w41, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #301: @22 = (@9*@41) */
  for (i=0, rr=w22, cs=w41; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #302: @18 = (@16*@47) */
  w18  = (w16*w47);
  /* #303: @63 = (@11*@43) */
  w63  = (w11*w43);
  /* #304: @18 = (@18-@63) */
  w18 -= w63;
  /* #305: @42 = (@34*@18) */
  for (i=0, rr=w42, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #306: @22 = (@22+@42) */
  for (i=0, rr=w22, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #307: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #308: @42 = (@35*@47) */
  for (i=0, rr=w42, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #309: @22 = (@22-@42) */
  for (i=0, rr=w22, cs=w42; i<3; ++i) (*rr++) -= (*cs++);
  /* #310: @42 = @22' */
  casadi_copy(w22, 3, w42);
  /* #311: @65 = mac(@42,@23,@1) */
  casadi_copy(w01, 3, w65);
  for (i=0, rr=w65; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #312: @65 = @65' */
  /* #313: @66 = mac(@42,@39,@1) */
  casadi_copy(w01, 3, w66);
  for (i=0, rr=w66; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #314: @66 = @66' */
  /* #315: @65 = (@65+@66) */
  for (i=0, rr=w65, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #316: @66 = (@65/@3) */
  for (i=0, rr=w66, cr=w65; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #317: @42 = (@40/@3) */
  for (i=0, rr=w42, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #318: @67 = (@42*@47) */
  for (i=0, rr=w67, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #319: @66 = (@66-@67) */
  for (i=0, rr=w66, cs=w67; i<3; ++i) (*rr++) -= (*cs++);
  /* #320: @63 = dot(@34, @66) */
  w63 = casadi_dot(3, w34, w66);
  /* #321: @68 = dot(@41, @40) */
  w68 = casadi_dot(3, w41, w40);
  /* #322: @63 = (@63+@68) */
  w63 += w68;
  /* #323: @68 = (@11*@63) */
  w68  = (w11*w63);
  /* #324: @46 = (@46+@68) */
  w46 += w68;
  /* #325: @46 = (-@46) */
  w46 = (- w46 );
  /* #326: @64 = @33; (@64[0] += @46) */
  casadi_copy(w33, 4, w64);
  for (rr=w64+0, cs=(&w46); rr!=w64+1; rr+=1) *rr += *cs++;
  /* #327: @46 = dot(@36, @65) */
  w46 = casadi_dot(3, w36, w65);
  /* #328: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #329: @65 = (@35/@3) */
  for (i=0, rr=w65, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #330: @41 = (@65*@47) */
  for (i=0, rr=w41, cr=w65; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #331: @22 = (@22-@41) */
  for (i=0, rr=w22, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #332: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #333: @68 = dot(@22, @37) */
  w68 = casadi_dot(3, w22, w37);
  /* #334: @46 = (@46+@68) */
  w46 += w68;
  /* #335: @43 = (@43/@10) */
  w43 /= w10;
  /* #336: @68 = (@16/@10) */
  w68  = (w16/w10);
  /* #337: @48 = (@68*@48) */
  w48  = (w68*w48);
  /* #338: @43 = (@43-@48) */
  w43 -= w48;
  /* #339: @43 = (@0*@43) */
  w43  = (w00*w43);
  /* #340: @63 = (@16*@63) */
  w63  = (w16*w63);
  /* #341: @43 = (@43+@63) */
  w43 += w63;
  /* #342: @46 = (@46+@43) */
  w46 += w43;
  /* #343: @46 = (@46/@14) */
  w46 /= w14;
  /* #344: @43 = (@2/@14) */
  w43  = (w02/w14);
  /* #345: @47 = (@43*@47) */
  w47  = (w43*w47);
  /* #346: @46 = (@46-@47) */
  w46 -= w47;
  /* #347: @22 = (@20*@46) */
  for (i=0, rr=w22, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #348: @25 = (@2*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #349: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #350: @25 = (@40*@18) */
  for (i=0, rr=w25, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #351: @66 = (@9*@66) */
  for (i=0, rr=w66, cs=w66; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #352: @25 = (@25+@66) */
  for (i=0, rr=w25, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #353: @25 = (2.*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #354: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #355: (@64[1:4] += @22) */
  for (rr=w64+1, cs=w22; rr!=w64+4; rr+=1) *rr += *cs++;
  /* #356: @61 = (@12?@64:0) */
  for (i=0, rr=w61, cs=w64; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #357: @64 = (-@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) *rr++ = (- *cs++ );
  /* #358: @64 = (@13?@64:0) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #359: @61 = (@61+@64) */
  for (i=0, rr=w61, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #360: {@18, @46, @47, @63} = vertsplit(@61) */
  w18 = w61[0];
  w46 = w61[1];
  w47 = w61[2];
  w63 = w61[3];
  /* #361: @48 = (@7*@63) */
  w48  = (w07*w63);
  /* #362: @69 = (@6*@47) */
  w69  = (w06*w47);
  /* #363: @48 = (@48+@69) */
  w48 += w69;
  /* #364: @69 = (@5*@46) */
  w69  = (w05*w46);
  /* #365: @48 = (@48+@69) */
  w48 += w69;
  /* #366: @69 = (@4*@18) */
  w69  = (w04*w18);
  /* #367: @48 = (@48+@69) */
  w48 += w69;
  /* #368: @69 = (@6*@63) */
  w69  = (w06*w63);
  /* #369: @70 = (@7*@47) */
  w70  = (w07*w47);
  /* #370: @69 = (@69-@70) */
  w69 -= w70;
  /* #371: @70 = (@4*@46) */
  w70  = (w04*w46);
  /* #372: @69 = (@69+@70) */
  w69 += w70;
  /* #373: @70 = (@5*@18) */
  w70  = (w05*w18);
  /* #374: @69 = (@69-@70) */
  w69 -= w70;
  /* #375: @70 = (@4*@47) */
  w70  = (w04*w47);
  /* #376: @71 = (@5*@63) */
  w71  = (w05*w63);
  /* #377: @70 = (@70-@71) */
  w70 -= w71;
  /* #378: @71 = (@7*@46) */
  w71  = (w07*w46);
  /* #379: @70 = (@70+@71) */
  w70 += w71;
  /* #380: @71 = (@6*@18) */
  w71  = (w06*w18);
  /* #381: @70 = (@70-@71) */
  w70 -= w71;
  /* #382: @63 = (@4*@63) */
  w63  = (w04*w63);
  /* #383: @47 = (@5*@47) */
  w47  = (w05*w47);
  /* #384: @63 = (@63+@47) */
  w63 += w47;
  /* #385: @46 = (@6*@46) */
  w46  = (w06*w46);
  /* #386: @63 = (@63-@46) */
  w63 -= w46;
  /* #387: @18 = (@7*@18) */
  w18  = (w07*w18);
  /* #388: @63 = (@63-@18) */
  w63 -= w18;
  /* #389: @61 = vertcat(@48, @69, @70, @63) */
  rr=w61;
  *rr++ = w48;
  *rr++ = w69;
  *rr++ = w70;
  *rr++ = w63;
  /* #390: @48 = dot(@30, @61) */
  w48 = casadi_dot(4, w30, w61);
  /* #391: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w08;
  /* #392: @64 = (@27/@8) */
  for (i=0, rr=w64, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #393: @72 = (@64*@51) */
  for (i=0, rr=w72, cr=w64; i<4; ++i) (*rr++)  = ((*cr++)*w51);
  /* #394: @60 = (@60-@72) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++) -= (*cs++);
  /* #395: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #396: @69 = dot(@60, @32) */
  w69 = casadi_dot(4, w60, w32);
  /* #397: @48 = (@48+@69) */
  w48 += w69;
  /* #398: @48 = (@48/@8) */
  w48 /= w08;
  /* #399: @69 = (@45/@8) */
  w69  = (w45/w08);
  /* #400: @70 = (@69*@51) */
  w70  = (w69*w51);
  /* #401: @48 = (@48-@70) */
  w48 -= w70;
  /* #402: @60 = (@31*@48) */
  for (i=0, rr=w60, cr=w31; i<4; ++i) (*rr++)  = ((*cr++)*w48);
  /* #403: @54 = (@45*@54) */
  w54  = (w45*w54);
  /* #404: @72 = dense(@54) */
  casadi_densify((&w54), casadi_s3, w72, 0);
  /* #405: @60 = (@60+@72) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #406: @49 = @21; (@49[6:10] += @60) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w60; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #407: @55 = sparsity_cast(@55) */
  /* #408: @55 = (-@55) */
  w55 = (- w55 );
  /* #409: @55 = @55' */
  /* #410: @22 = mac(@55,@24,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w55), casadi_s6, w24, casadi_s5, w22, casadi_s4, w, 0);
  /* #411: @22 = @22' */
  /* #412: @25 = mac(@55,@50,@1) */
  casadi_copy(w01, 3, w25);
  casadi_mtimes((&w55), casadi_s6, w50, casadi_s5, w25, casadi_s4, w, 0);
  /* #413: @25 = @25' */
  /* #414: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #415: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #416: (@49[:3] += @22) */
  for (rr=w49+0, cs=w22; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #417: {@55, @54, @48, @70, @63, @18, @46, @47, @71, @73, @74, @75, @76} = vertsplit(@49) */
  w55 = w49[0];
  w54 = w49[1];
  w48 = w49[2];
  w70 = w49[3];
  w63 = w49[4];
  w18 = w49[5];
  w46 = w49[6];
  w47 = w49[7];
  w71 = w49[8];
  w73 = w49[9];
  w74 = w49[10];
  w75 = w49[11];
  w76 = w49[12];
  /* #418: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #419: @28 = (@28/@8) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) /= w08;
  /* #420: @60 = (@28*@51) */
  for (i=0, rr=w60, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w51);
  /* #421: @61 = (@61-@60) */
  for (i=0, rr=w61, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #422: {@51, @77, @78, @79} = vertsplit(@61) */
  w51 = w61[0];
  w77 = w61[1];
  w78 = w61[2];
  w79 = w61[3];
  /* #423: @51 = (@51+@46) */
  w51 += w46;
  /* #424: @47 = (@47-@77) */
  w47 -= w77;
  /* #425: @71 = (@71-@78) */
  w71 -= w78;
  /* #426: @73 = (@73-@79) */
  w73 -= w79;
  /* #427: @19 = vertcat(@53, @56, @44, @52, @55, @54, @48, @70, @63, @18, @51, @47, @71, @73, @74, @75, @76) */
  rr=w19;
  *rr++ = w53;
  *rr++ = w56;
  *rr++ = w44;
  *rr++ = w52;
  *rr++ = w55;
  *rr++ = w54;
  *rr++ = w48;
  *rr++ = w70;
  *rr++ = w63;
  *rr++ = w18;
  *rr++ = w51;
  *rr++ = w47;
  *rr++ = w71;
  *rr++ = w73;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w76;
  /* #428: @80 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w80, cs=w19; cii!=casadi_s7+11; ++cii) *rr++ = cs[*cii];
  /* #429: (@57[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @80) */
  for (cii=casadi_s8, rr=w57, cs=w80; cii!=casadi_s8+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #430: (@57[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @80) */
  for (cii=casadi_s9, rr=w57, cs=w80; cii!=casadi_s9+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #431: @22 = ones(17x1,3nz) */
  casadi_fill(w22, 3, 1.);
  /* #432: {NULL, @53, NULL, NULL, NULL, @56, NULL, NULL, NULL, NULL, NULL, @44, NULL, NULL, NULL, NULL, NULL} = vertsplit(@22) */
  w53 = w22[0];
  w56 = w22[1];
  w44 = w22[2];
  /* #433: @52 = vertcat(@59, @53, @59, @59) */
  rr=(&w52);
  *rr++ = w53;
  /* #434: @52 = @52' */
  /* #435: @61 = mac(@52,@29,@26) */
  casadi_copy(w26, 4, w61);
  casadi_mtimes((&w52), casadi_s10, w29, casadi_s1, w61, casadi_s0, w, 0);
  /* #436: @61 = @61' */
  /* #437: @60 = mac(@52,@38,@26) */
  casadi_copy(w26, 4, w60);
  casadi_mtimes((&w52), casadi_s10, w38, casadi_s1, w60, casadi_s0, w, 0);
  /* #438: @60 = @60' */
  /* #439: @61 = (@61+@60) */
  for (i=0, rr=w61, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #440: {@52, @53, @55, @54} = vertsplit(@61) */
  w52 = w61[0];
  w53 = w61[1];
  w55 = w61[2];
  w54 = w61[3];
  /* #441: @48 = (-@44) */
  w48 = (- w44 );
  /* #442: @70 = vertcat(@59, @48, @59, @59) */
  rr=(&w70);
  *rr++ = w48;
  /* #443: @70 = (@70/@8) */
  w70 /= w08;
  /* #444: @61 = dense(@70) */
  casadi_densify((&w70), casadi_s11, w61, 0);
  /* #445: @70 = project(@31) */
  casadi_sparsify(w31, (&w70), casadi_s11, 0);
  /* #446: @44 = sparsity_cast(@44) */
  /* #447: @48 = dot(@70, @44) */
  w48 = casadi_dot(1, (&w70), (&w44));
  /* #448: @48 = (@48/@8) */
  w48 /= w08;
  /* #449: @60 = (@27*@48) */
  for (i=0, rr=w60, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w48);
  /* #450: @61 = (@61-@60) */
  for (i=0, rr=w61, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #451: {@70, @63, @18, @51} = vertsplit(@61) */
  w70 = w61[0];
  w63 = w61[1];
  w18 = w61[2];
  w51 = w61[3];
  /* #452: @47 = (@4*@70) */
  w47  = (w04*w70);
  /* #453: @71 = (@5*@63) */
  w71  = (w05*w63);
  /* #454: @47 = (@47-@71) */
  w47 -= w71;
  /* #455: @71 = (@6*@18) */
  w71  = (w06*w18);
  /* #456: @47 = (@47-@71) */
  w47 -= w71;
  /* #457: @71 = (@7*@51) */
  w71  = (w07*w51);
  /* #458: @47 = (@47-@71) */
  w47 -= w71;
  /* #459: @71 = (@5*@70) */
  w71  = (w05*w70);
  /* #460: @73 = (@4*@63) */
  w73  = (w04*w63);
  /* #461: @71 = (@71+@73) */
  w71 += w73;
  /* #462: @73 = (@7*@18) */
  w73  = (w07*w18);
  /* #463: @71 = (@71+@73) */
  w71 += w73;
  /* #464: @73 = (@6*@51) */
  w73  = (w06*w51);
  /* #465: @71 = (@71-@73) */
  w71 -= w73;
  /* #466: @73 = (@6*@70) */
  w73  = (w06*w70);
  /* #467: @74 = (@7*@63) */
  w74  = (w07*w63);
  /* #468: @73 = (@73-@74) */
  w73 -= w74;
  /* #469: @74 = (@4*@18) */
  w74  = (w04*w18);
  /* #470: @73 = (@73+@74) */
  w73 += w74;
  /* #471: @74 = (@5*@51) */
  w74  = (w05*w51);
  /* #472: @73 = (@73+@74) */
  w73 += w74;
  /* #473: @70 = (@7*@70) */
  w70  = (w07*w70);
  /* #474: @63 = (@6*@63) */
  w63  = (w06*w63);
  /* #475: @70 = (@70+@63) */
  w70 += w63;
  /* #476: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #477: @70 = (@70-@18) */
  w70 -= w18;
  /* #478: @51 = (@4*@51) */
  w51  = (w04*w51);
  /* #479: @70 = (@70+@51) */
  w70 += w51;
  /* #480: @60 = vertcat(@47, @71, @73, @70) */
  rr=w60;
  *rr++ = w47;
  *rr++ = w71;
  *rr++ = w73;
  *rr++ = w70;
  /* #481: @72 = (-@60) */
  for (i=0, rr=w72, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #482: @72 = (@13?@72:0) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #483: @60 = (@12?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #484: @72 = (@72+@60) */
  for (i=0, rr=w72, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #485: @22 = @72[1:4] */
  for (rr=w22, cs=w72+1; cs!=w72+4; cs+=1) *rr++ = *cs;
  /* #486: @47 = dot(@20, @22) */
  w47 = casadi_dot(3, w20, w22);
  /* #487: @47 = (@47/@14) */
  w47 /= w14;
  /* #488: @71 = (@47/@10) */
  w71  = (w47/w10);
  /* #489: @73 = (@17*@47) */
  w73  = (w17*w47);
  /* #490: @70 = @72[0] */
  for (rr=(&w70), cs=w72+0; cs!=w72+1; cs+=1) *rr++ = *cs;
  /* #491: @51 = (@15*@70) */
  w51  = (w15*w70);
  /* #492: @73 = (@73+@51) */
  w73 += w51;
  /* #493: @51 = (@62*@73) */
  w51  = (w62*w73);
  /* #494: @71 = (@71-@51) */
  w71 -= w51;
  /* #495: @71 = (@0*@71) */
  w71  = (w00*w71);
  /* #496: @25 = (2.*@22) */
  for (i=0, rr=w25, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #497: @66 = (@9*@25) */
  for (i=0, rr=w66, cs=w25; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #498: @51 = (@16*@47) */
  w51  = (w16*w47);
  /* #499: @18 = (@11*@70) */
  w18  = (w11*w70);
  /* #500: @51 = (@51-@18) */
  w51 -= w18;
  /* #501: @41 = (@34*@51) */
  for (i=0, rr=w41, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w51);
  /* #502: @66 = (@66+@41) */
  for (i=0, rr=w66, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #503: @66 = (@66/@3) */
  for (i=0, rr=w66; i<3; ++i) (*rr++) /= w03;
  /* #504: @41 = (@35*@47) */
  for (i=0, rr=w41, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #505: @66 = (@66-@41) */
  for (i=0, rr=w66, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #506: @41 = @66' */
  casadi_copy(w66, 3, w41);
  /* #507: @67 = mac(@41,@23,@1) */
  casadi_copy(w01, 3, w67);
  for (i=0, rr=w67; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #508: @67 = @67' */
  /* #509: @81 = mac(@41,@39,@1) */
  casadi_copy(w01, 3, w81);
  for (i=0, rr=w81; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #510: @81 = @81' */
  /* #511: @67 = (@67+@81) */
  for (i=0, rr=w67, cs=w81; i<3; ++i) (*rr++) += (*cs++);
  /* #512: @81 = (@67/@3) */
  for (i=0, rr=w81, cr=w67; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #513: @41 = (@42*@47) */
  for (i=0, rr=w41, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #514: @81 = (@81-@41) */
  for (i=0, rr=w81, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #515: @18 = dot(@34, @81) */
  w18 = casadi_dot(3, w34, w81);
  /* #516: @63 = dot(@25, @40) */
  w63 = casadi_dot(3, w25, w40);
  /* #517: @18 = (@18+@63) */
  w18 += w63;
  /* #518: @63 = (@11*@18) */
  w63  = (w11*w18);
  /* #519: @71 = (@71+@63) */
  w71 += w63;
  /* #520: @71 = (-@71) */
  w71 = (- w71 );
  /* #521: @72 = @33; (@72[0] += @71) */
  casadi_copy(w33, 4, w72);
  for (rr=w72+0, cs=(&w71); rr!=w72+1; rr+=1) *rr += *cs++;
  /* #522: @71 = dot(@36, @67) */
  w71 = casadi_dot(3, w36, w67);
  /* #523: @66 = (@66/@3) */
  for (i=0, rr=w66; i<3; ++i) (*rr++) /= w03;
  /* #524: @67 = (@65*@47) */
  for (i=0, rr=w67, cr=w65; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #525: @66 = (@66-@67) */
  for (i=0, rr=w66, cs=w67; i<3; ++i) (*rr++) -= (*cs++);
  /* #526: @66 = (-@66) */
  for (i=0, rr=w66, cs=w66; i<3; ++i) *rr++ = (- *cs++ );
  /* #527: @63 = dot(@66, @37) */
  w63 = casadi_dot(3, w66, w37);
  /* #528: @71 = (@71+@63) */
  w71 += w63;
  /* #529: @70 = (@70/@10) */
  w70 /= w10;
  /* #530: @73 = (@68*@73) */
  w73  = (w68*w73);
  /* #531: @70 = (@70-@73) */
  w70 -= w73;
  /* #532: @70 = (@0*@70) */
  w70  = (w00*w70);
  /* #533: @18 = (@16*@18) */
  w18  = (w16*w18);
  /* #534: @70 = (@70+@18) */
  w70 += w18;
  /* #535: @71 = (@71+@70) */
  w71 += w70;
  /* #536: @71 = (@71/@14) */
  w71 /= w14;
  /* #537: @47 = (@43*@47) */
  w47  = (w43*w47);
  /* #538: @71 = (@71-@47) */
  w71 -= w47;
  /* #539: @66 = (@20*@71) */
  for (i=0, rr=w66, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w71);
  /* #540: @22 = (@2*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #541: @66 = (@66+@22) */
  for (i=0, rr=w66, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #542: @22 = (@40*@51) */
  for (i=0, rr=w22, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w51);
  /* #543: @81 = (@9*@81) */
  for (i=0, rr=w81, cs=w81; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #544: @22 = (@22+@81) */
  for (i=0, rr=w22, cs=w81; i<3; ++i) (*rr++) += (*cs++);
  /* #545: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #546: @66 = (@66+@22) */
  for (i=0, rr=w66, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #547: (@72[1:4] += @66) */
  for (rr=w72+1, cs=w66; rr!=w72+4; rr+=1) *rr += *cs++;
  /* #548: @60 = (@12?@72:0) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #549: @72 = (-@72) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) *rr++ = (- *cs++ );
  /* #550: @72 = (@13?@72:0) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #551: @60 = (@60+@72) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #552: {@51, @71, @47, @70} = vertsplit(@60) */
  w51 = w60[0];
  w71 = w60[1];
  w47 = w60[2];
  w70 = w60[3];
  /* #553: @18 = (@7*@70) */
  w18  = (w07*w70);
  /* #554: @73 = (@6*@47) */
  w73  = (w06*w47);
  /* #555: @18 = (@18+@73) */
  w18 += w73;
  /* #556: @73 = (@5*@71) */
  w73  = (w05*w71);
  /* #557: @18 = (@18+@73) */
  w18 += w73;
  /* #558: @73 = (@4*@51) */
  w73  = (w04*w51);
  /* #559: @18 = (@18+@73) */
  w18 += w73;
  /* #560: @73 = (@6*@70) */
  w73  = (w06*w70);
  /* #561: @63 = (@7*@47) */
  w63  = (w07*w47);
  /* #562: @73 = (@73-@63) */
  w73 -= w63;
  /* #563: @63 = (@4*@71) */
  w63  = (w04*w71);
  /* #564: @73 = (@73+@63) */
  w73 += w63;
  /* #565: @63 = (@5*@51) */
  w63  = (w05*w51);
  /* #566: @73 = (@73-@63) */
  w73 -= w63;
  /* #567: @63 = (@4*@47) */
  w63  = (w04*w47);
  /* #568: @74 = (@5*@70) */
  w74  = (w05*w70);
  /* #569: @63 = (@63-@74) */
  w63 -= w74;
  /* #570: @74 = (@7*@71) */
  w74  = (w07*w71);
  /* #571: @63 = (@63+@74) */
  w63 += w74;
  /* #572: @74 = (@6*@51) */
  w74  = (w06*w51);
  /* #573: @63 = (@63-@74) */
  w63 -= w74;
  /* #574: @70 = (@4*@70) */
  w70  = (w04*w70);
  /* #575: @47 = (@5*@47) */
  w47  = (w05*w47);
  /* #576: @70 = (@70+@47) */
  w70 += w47;
  /* #577: @71 = (@6*@71) */
  w71  = (w06*w71);
  /* #578: @70 = (@70-@71) */
  w70 -= w71;
  /* #579: @51 = (@7*@51) */
  w51  = (w07*w51);
  /* #580: @70 = (@70-@51) */
  w70 -= w51;
  /* #581: @60 = vertcat(@18, @73, @63, @70) */
  rr=w60;
  *rr++ = w18;
  *rr++ = w73;
  *rr++ = w63;
  *rr++ = w70;
  /* #582: @18 = dot(@30, @60) */
  w18 = casadi_dot(4, w30, w60);
  /* #583: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #584: @72 = (@64*@48) */
  for (i=0, rr=w72, cr=w64; i<4; ++i) (*rr++)  = ((*cr++)*w48);
  /* #585: @61 = (@61-@72) */
  for (i=0, rr=w61, cs=w72; i<4; ++i) (*rr++) -= (*cs++);
  /* #586: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #587: @73 = dot(@61, @32) */
  w73 = casadi_dot(4, w61, w32);
  /* #588: @18 = (@18+@73) */
  w18 += w73;
  /* #589: @18 = (@18/@8) */
  w18 /= w08;
  /* #590: @73 = (@69*@48) */
  w73  = (w69*w48);
  /* #591: @18 = (@18-@73) */
  w18 -= w73;
  /* #592: @61 = (@31*@18) */
  for (i=0, rr=w61, cr=w31; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #593: @44 = (@45*@44) */
  w44  = (w45*w44);
  /* #594: @72 = dense(@44) */
  casadi_densify((&w44), casadi_s11, w72, 0);
  /* #595: @61 = (@61+@72) */
  for (i=0, rr=w61, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #596: @49 = @21; (@49[6:10] += @61) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w61; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #597: @56 = sparsity_cast(@56) */
  /* #598: @56 = (-@56) */
  w56 = (- w56 );
  /* #599: @56 = @56' */
  /* #600: @66 = mac(@56,@24,@1) */
  casadi_copy(w01, 3, w66);
  casadi_mtimes((&w56), casadi_s12, w24, casadi_s5, w66, casadi_s4, w, 0);
  /* #601: @66 = @66' */
  /* #602: @22 = mac(@56,@50,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w56), casadi_s12, w50, casadi_s5, w22, casadi_s4, w, 0);
  /* #603: @22 = @22' */
  /* #604: @66 = (@66+@22) */
  for (i=0, rr=w66, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #605: @66 = (-@66) */
  for (i=0, rr=w66, cs=w66; i<3; ++i) *rr++ = (- *cs++ );
  /* #606: (@49[:3] += @66) */
  for (rr=w49+0, cs=w66; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #607: {@56, @44, @18, @73, @63, @70, @51, @71, @47, @74, @75, @76, @79} = vertsplit(@49) */
  w56 = w49[0];
  w44 = w49[1];
  w18 = w49[2];
  w73 = w49[3];
  w63 = w49[4];
  w70 = w49[5];
  w51 = w49[6];
  w71 = w49[7];
  w47 = w49[8];
  w74 = w49[9];
  w75 = w49[10];
  w76 = w49[11];
  w79 = w49[12];
  /* #608: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w08;
  /* #609: @61 = (@28*@48) */
  for (i=0, rr=w61, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w48);
  /* #610: @60 = (@60-@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #611: {@48, @78, @77, @46} = vertsplit(@60) */
  w48 = w60[0];
  w78 = w60[1];
  w77 = w60[2];
  w46 = w60[3];
  /* #612: @48 = (@48+@51) */
  w48 += w51;
  /* #613: @71 = (@71-@78) */
  w71 -= w78;
  /* #614: @47 = (@47-@77) */
  w47 -= w77;
  /* #615: @74 = (@74-@46) */
  w74 -= w46;
  /* #616: @19 = vertcat(@52, @53, @55, @54, @56, @44, @18, @73, @63, @70, @48, @71, @47, @74, @75, @76, @79) */
  rr=w19;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w55;
  *rr++ = w54;
  *rr++ = w56;
  *rr++ = w44;
  *rr++ = w18;
  *rr++ = w73;
  *rr++ = w63;
  *rr++ = w70;
  *rr++ = w48;
  *rr++ = w71;
  *rr++ = w47;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w76;
  *rr++ = w79;
  /* #617: @80 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w80, cs=w19; cii!=casadi_s7+11; ++cii) *rr++ = cs[*cii];
  /* #618: (@57[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @80) */
  for (cii=casadi_s13, rr=w57, cs=w80; cii!=casadi_s13+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #619: (@57[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @80) */
  for (cii=casadi_s14, rr=w57, cs=w80; cii!=casadi_s14+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #620: @66 = ones(17x1,3nz) */
  casadi_fill(w66, 3, 1.);
  /* #621: {NULL, NULL, @52, NULL, NULL, NULL, @53, NULL, NULL, NULL, NULL, NULL, @55, NULL, NULL, NULL, NULL} = vertsplit(@66) */
  w52 = w66[0];
  w53 = w66[1];
  w55 = w66[2];
  /* #622: @54 = vertcat(@59, @59, @52, @59) */
  rr=(&w54);
  *rr++ = w52;
  /* #623: @54 = @54' */
  /* #624: @60 = mac(@54,@29,@26) */
  casadi_copy(w26, 4, w60);
  casadi_mtimes((&w54), casadi_s15, w29, casadi_s1, w60, casadi_s0, w, 0);
  /* #625: @60 = @60' */
  /* #626: @61 = mac(@54,@38,@26) */
  casadi_copy(w26, 4, w61);
  casadi_mtimes((&w54), casadi_s15, w38, casadi_s1, w61, casadi_s0, w, 0);
  /* #627: @61 = @61' */
  /* #628: @60 = (@60+@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #629: {@54, @52, @56, @44} = vertsplit(@60) */
  w54 = w60[0];
  w52 = w60[1];
  w56 = w60[2];
  w44 = w60[3];
  /* #630: @18 = (-@55) */
  w18 = (- w55 );
  /* #631: @73 = vertcat(@59, @59, @18, @59) */
  rr=(&w73);
  *rr++ = w18;
  /* #632: @73 = (@73/@8) */
  w73 /= w08;
  /* #633: @60 = dense(@73) */
  casadi_densify((&w73), casadi_s16, w60, 0);
  /* #634: @73 = project(@31) */
  casadi_sparsify(w31, (&w73), casadi_s16, 0);
  /* #635: @55 = sparsity_cast(@55) */
  /* #636: @18 = dot(@73, @55) */
  w18 = casadi_dot(1, (&w73), (&w55));
  /* #637: @18 = (@18/@8) */
  w18 /= w08;
  /* #638: @61 = (@27*@18) */
  for (i=0, rr=w61, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #639: @60 = (@60-@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #640: {@73, @63, @70, @48} = vertsplit(@60) */
  w73 = w60[0];
  w63 = w60[1];
  w70 = w60[2];
  w48 = w60[3];
  /* #641: @71 = (@4*@73) */
  w71  = (w04*w73);
  /* #642: @47 = (@5*@63) */
  w47  = (w05*w63);
  /* #643: @71 = (@71-@47) */
  w71 -= w47;
  /* #644: @47 = (@6*@70) */
  w47  = (w06*w70);
  /* #645: @71 = (@71-@47) */
  w71 -= w47;
  /* #646: @47 = (@7*@48) */
  w47  = (w07*w48);
  /* #647: @71 = (@71-@47) */
  w71 -= w47;
  /* #648: @47 = (@5*@73) */
  w47  = (w05*w73);
  /* #649: @74 = (@4*@63) */
  w74  = (w04*w63);
  /* #650: @47 = (@47+@74) */
  w47 += w74;
  /* #651: @74 = (@7*@70) */
  w74  = (w07*w70);
  /* #652: @47 = (@47+@74) */
  w47 += w74;
  /* #653: @74 = (@6*@48) */
  w74  = (w06*w48);
  /* #654: @47 = (@47-@74) */
  w47 -= w74;
  /* #655: @74 = (@6*@73) */
  w74  = (w06*w73);
  /* #656: @75 = (@7*@63) */
  w75  = (w07*w63);
  /* #657: @74 = (@74-@75) */
  w74 -= w75;
  /* #658: @75 = (@4*@70) */
  w75  = (w04*w70);
  /* #659: @74 = (@74+@75) */
  w74 += w75;
  /* #660: @75 = (@5*@48) */
  w75  = (w05*w48);
  /* #661: @74 = (@74+@75) */
  w74 += w75;
  /* #662: @73 = (@7*@73) */
  w73  = (w07*w73);
  /* #663: @63 = (@6*@63) */
  w63  = (w06*w63);
  /* #664: @73 = (@73+@63) */
  w73 += w63;
  /* #665: @70 = (@5*@70) */
  w70  = (w05*w70);
  /* #666: @73 = (@73-@70) */
  w73 -= w70;
  /* #667: @48 = (@4*@48) */
  w48  = (w04*w48);
  /* #668: @73 = (@73+@48) */
  w73 += w48;
  /* #669: @61 = vertcat(@71, @47, @74, @73) */
  rr=w61;
  *rr++ = w71;
  *rr++ = w47;
  *rr++ = w74;
  *rr++ = w73;
  /* #670: @72 = (-@61) */
  for (i=0, rr=w72, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #671: @72 = (@13?@72:0) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #672: @61 = (@12?@61:0) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #673: @72 = (@72+@61) */
  for (i=0, rr=w72, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #674: @66 = @72[1:4] */
  for (rr=w66, cs=w72+1; cs!=w72+4; cs+=1) *rr++ = *cs;
  /* #675: @71 = dot(@20, @66) */
  w71 = casadi_dot(3, w20, w66);
  /* #676: @71 = (@71/@14) */
  w71 /= w14;
  /* #677: @47 = (@71/@10) */
  w47  = (w71/w10);
  /* #678: @74 = (@17*@71) */
  w74  = (w17*w71);
  /* #679: @73 = @72[0] */
  for (rr=(&w73), cs=w72+0; cs!=w72+1; cs+=1) *rr++ = *cs;
  /* #680: @48 = (@15*@73) */
  w48  = (w15*w73);
  /* #681: @74 = (@74+@48) */
  w74 += w48;
  /* #682: @48 = (@62*@74) */
  w48  = (w62*w74);
  /* #683: @47 = (@47-@48) */
  w47 -= w48;
  /* #684: @47 = (@0*@47) */
  w47  = (w00*w47);
  /* #685: @22 = (2.*@66) */
  for (i=0, rr=w22, cs=w66; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #686: @81 = (@9*@22) */
  for (i=0, rr=w81, cs=w22; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #687: @48 = (@16*@71) */
  w48  = (w16*w71);
  /* #688: @70 = (@11*@73) */
  w70  = (w11*w73);
  /* #689: @48 = (@48-@70) */
  w48 -= w70;
  /* #690: @67 = (@34*@48) */
  for (i=0, rr=w67, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #691: @81 = (@81+@67) */
  for (i=0, rr=w81, cs=w67; i<3; ++i) (*rr++) += (*cs++);
  /* #692: @81 = (@81/@3) */
  for (i=0, rr=w81; i<3; ++i) (*rr++) /= w03;
  /* #693: @67 = (@35*@71) */
  for (i=0, rr=w67, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w71);
  /* #694: @81 = (@81-@67) */
  for (i=0, rr=w81, cs=w67; i<3; ++i) (*rr++) -= (*cs++);
  /* #695: @67 = @81' */
  casadi_copy(w81, 3, w67);
  /* #696: @25 = mac(@67,@23,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w67+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #697: @25 = @25' */
  /* #698: @41 = mac(@67,@39,@1) */
  casadi_copy(w01, 3, w41);
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w67+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #699: @41 = @41' */
  /* #700: @25 = (@25+@41) */
  for (i=0, rr=w25, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #701: @41 = (@25/@3) */
  for (i=0, rr=w41, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #702: @67 = (@42*@71) */
  for (i=0, rr=w67, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w71);
  /* #703: @41 = (@41-@67) */
  for (i=0, rr=w41, cs=w67; i<3; ++i) (*rr++) -= (*cs++);
  /* #704: @70 = dot(@34, @41) */
  w70 = casadi_dot(3, w34, w41);
  /* #705: @63 = dot(@22, @40) */
  w63 = casadi_dot(3, w22, w40);
  /* #706: @70 = (@70+@63) */
  w70 += w63;
  /* #707: @63 = (@11*@70) */
  w63  = (w11*w70);
  /* #708: @47 = (@47+@63) */
  w47 += w63;
  /* #709: @47 = (-@47) */
  w47 = (- w47 );
  /* #710: @72 = @33; (@72[0] += @47) */
  casadi_copy(w33, 4, w72);
  for (rr=w72+0, cs=(&w47); rr!=w72+1; rr+=1) *rr += *cs++;
  /* #711: @47 = dot(@36, @25) */
  w47 = casadi_dot(3, w36, w25);
  /* #712: @81 = (@81/@3) */
  for (i=0, rr=w81; i<3; ++i) (*rr++) /= w03;
  /* #713: @25 = (@65*@71) */
  for (i=0, rr=w25, cr=w65; i<3; ++i) (*rr++)  = ((*cr++)*w71);
  /* #714: @81 = (@81-@25) */
  for (i=0, rr=w81, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #715: @81 = (-@81) */
  for (i=0, rr=w81, cs=w81; i<3; ++i) *rr++ = (- *cs++ );
  /* #716: @63 = dot(@81, @37) */
  w63 = casadi_dot(3, w81, w37);
  /* #717: @47 = (@47+@63) */
  w47 += w63;
  /* #718: @73 = (@73/@10) */
  w73 /= w10;
  /* #719: @74 = (@68*@74) */
  w74  = (w68*w74);
  /* #720: @73 = (@73-@74) */
  w73 -= w74;
  /* #721: @73 = (@0*@73) */
  w73  = (w00*w73);
  /* #722: @70 = (@16*@70) */
  w70  = (w16*w70);
  /* #723: @73 = (@73+@70) */
  w73 += w70;
  /* #724: @47 = (@47+@73) */
  w47 += w73;
  /* #725: @47 = (@47/@14) */
  w47 /= w14;
  /* #726: @71 = (@43*@71) */
  w71  = (w43*w71);
  /* #727: @47 = (@47-@71) */
  w47 -= w71;
  /* #728: @81 = (@20*@47) */
  for (i=0, rr=w81, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #729: @66 = (@2*@66) */
  for (i=0, rr=w66, cs=w66; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #730: @81 = (@81+@66) */
  for (i=0, rr=w81, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #731: @66 = (@40*@48) */
  for (i=0, rr=w66, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #732: @41 = (@9*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #733: @66 = (@66+@41) */
  for (i=0, rr=w66, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #734: @66 = (2.*@66) */
  for (i=0, rr=w66, cs=w66; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #735: @81 = (@81+@66) */
  for (i=0, rr=w81, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #736: (@72[1:4] += @81) */
  for (rr=w72+1, cs=w81; rr!=w72+4; rr+=1) *rr += *cs++;
  /* #737: @61 = (@12?@72:0) */
  for (i=0, rr=w61, cs=w72; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #738: @72 = (-@72) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) *rr++ = (- *cs++ );
  /* #739: @72 = (@13?@72:0) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #740: @61 = (@61+@72) */
  for (i=0, rr=w61, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #741: {@48, @47, @71, @73} = vertsplit(@61) */
  w48 = w61[0];
  w47 = w61[1];
  w71 = w61[2];
  w73 = w61[3];
  /* #742: @70 = (@7*@73) */
  w70  = (w07*w73);
  /* #743: @74 = (@6*@71) */
  w74  = (w06*w71);
  /* #744: @70 = (@70+@74) */
  w70 += w74;
  /* #745: @74 = (@5*@47) */
  w74  = (w05*w47);
  /* #746: @70 = (@70+@74) */
  w70 += w74;
  /* #747: @74 = (@4*@48) */
  w74  = (w04*w48);
  /* #748: @70 = (@70+@74) */
  w70 += w74;
  /* #749: @74 = (@6*@73) */
  w74  = (w06*w73);
  /* #750: @63 = (@7*@71) */
  w63  = (w07*w71);
  /* #751: @74 = (@74-@63) */
  w74 -= w63;
  /* #752: @63 = (@4*@47) */
  w63  = (w04*w47);
  /* #753: @74 = (@74+@63) */
  w74 += w63;
  /* #754: @63 = (@5*@48) */
  w63  = (w05*w48);
  /* #755: @74 = (@74-@63) */
  w74 -= w63;
  /* #756: @63 = (@4*@71) */
  w63  = (w04*w71);
  /* #757: @75 = (@5*@73) */
  w75  = (w05*w73);
  /* #758: @63 = (@63-@75) */
  w63 -= w75;
  /* #759: @75 = (@7*@47) */
  w75  = (w07*w47);
  /* #760: @63 = (@63+@75) */
  w63 += w75;
  /* #761: @75 = (@6*@48) */
  w75  = (w06*w48);
  /* #762: @63 = (@63-@75) */
  w63 -= w75;
  /* #763: @73 = (@4*@73) */
  w73  = (w04*w73);
  /* #764: @71 = (@5*@71) */
  w71  = (w05*w71);
  /* #765: @73 = (@73+@71) */
  w73 += w71;
  /* #766: @47 = (@6*@47) */
  w47  = (w06*w47);
  /* #767: @73 = (@73-@47) */
  w73 -= w47;
  /* #768: @48 = (@7*@48) */
  w48  = (w07*w48);
  /* #769: @73 = (@73-@48) */
  w73 -= w48;
  /* #770: @61 = vertcat(@70, @74, @63, @73) */
  rr=w61;
  *rr++ = w70;
  *rr++ = w74;
  *rr++ = w63;
  *rr++ = w73;
  /* #771: @70 = dot(@30, @61) */
  w70 = casadi_dot(4, w30, w61);
  /* #772: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w08;
  /* #773: @72 = (@64*@18) */
  for (i=0, rr=w72, cr=w64; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #774: @60 = (@60-@72) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++) -= (*cs++);
  /* #775: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #776: @74 = dot(@60, @32) */
  w74 = casadi_dot(4, w60, w32);
  /* #777: @70 = (@70+@74) */
  w70 += w74;
  /* #778: @70 = (@70/@8) */
  w70 /= w08;
  /* #779: @74 = (@69*@18) */
  w74  = (w69*w18);
  /* #780: @70 = (@70-@74) */
  w70 -= w74;
  /* #781: @60 = (@31*@70) */
  for (i=0, rr=w60, cr=w31; i<4; ++i) (*rr++)  = ((*cr++)*w70);
  /* #782: @55 = (@45*@55) */
  w55  = (w45*w55);
  /* #783: @72 = dense(@55) */
  casadi_densify((&w55), casadi_s16, w72, 0);
  /* #784: @60 = (@60+@72) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #785: @49 = @21; (@49[6:10] += @60) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w60; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #786: @53 = sparsity_cast(@53) */
  /* #787: @53 = (-@53) */
  w53 = (- w53 );
  /* #788: @53 = @53' */
  /* #789: @81 = mac(@53,@24,@1) */
  casadi_copy(w01, 3, w81);
  casadi_mtimes((&w53), casadi_s17, w24, casadi_s5, w81, casadi_s4, w, 0);
  /* #790: @81 = @81' */
  /* #791: @66 = mac(@53,@50,@1) */
  casadi_copy(w01, 3, w66);
  casadi_mtimes((&w53), casadi_s17, w50, casadi_s5, w66, casadi_s4, w, 0);
  /* #792: @66 = @66' */
  /* #793: @81 = (@81+@66) */
  for (i=0, rr=w81, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #794: @81 = (-@81) */
  for (i=0, rr=w81, cs=w81; i<3; ++i) *rr++ = (- *cs++ );
  /* #795: (@49[:3] += @81) */
  for (rr=w49+0, cs=w81; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #796: {@53, @55, @70, @74, @63, @73, @48, @47, @71, @75, @76, @79, @46} = vertsplit(@49) */
  w53 = w49[0];
  w55 = w49[1];
  w70 = w49[2];
  w74 = w49[3];
  w63 = w49[4];
  w73 = w49[5];
  w48 = w49[6];
  w47 = w49[7];
  w71 = w49[8];
  w75 = w49[9];
  w76 = w49[10];
  w79 = w49[11];
  w46 = w49[12];
  /* #797: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #798: @60 = (@28*@18) */
  for (i=0, rr=w60, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #799: @61 = (@61-@60) */
  for (i=0, rr=w61, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #800: {@18, @77, @78, @51} = vertsplit(@61) */
  w18 = w61[0];
  w77 = w61[1];
  w78 = w61[2];
  w51 = w61[3];
  /* #801: @18 = (@18+@48) */
  w18 += w48;
  /* #802: @47 = (@47-@77) */
  w47 -= w77;
  /* #803: @71 = (@71-@78) */
  w71 -= w78;
  /* #804: @75 = (@75-@51) */
  w75 -= w51;
  /* #805: @19 = vertcat(@54, @52, @56, @44, @53, @55, @70, @74, @63, @73, @18, @47, @71, @75, @76, @79, @46) */
  rr=w19;
  *rr++ = w54;
  *rr++ = w52;
  *rr++ = w56;
  *rr++ = w44;
  *rr++ = w53;
  *rr++ = w55;
  *rr++ = w70;
  *rr++ = w74;
  *rr++ = w63;
  *rr++ = w73;
  *rr++ = w18;
  *rr++ = w47;
  *rr++ = w71;
  *rr++ = w75;
  *rr++ = w76;
  *rr++ = w79;
  *rr++ = w46;
  /* #806: @80 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w80, cs=w19; cii!=casadi_s7+11; ++cii) *rr++ = cs[*cii];
  /* #807: (@57[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @80) */
  for (cii=casadi_s18, rr=w57, cs=w80; cii!=casadi_s18+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #808: (@57[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @80) */
  for (cii=casadi_s19, rr=w57, cs=w80; cii!=casadi_s19+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #809: @82 = ones(17x1,2nz) */
  casadi_fill(w82, 2, 1.);
  /* #810: {NULL, NULL, NULL, @54, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @52, NULL, NULL, NULL} = vertsplit(@82) */
  w54 = w82[0];
  w52 = w82[1];
  /* #811: @56 = vertcat(@59, @59, @59, @54) */
  rr=(&w56);
  *rr++ = w54;
  /* #812: @56 = @56' */
  /* #813: @61 = mac(@56,@29,@26) */
  casadi_copy(w26, 4, w61);
  casadi_mtimes((&w56), casadi_s20, w29, casadi_s1, w61, casadi_s0, w, 0);
  /* #814: @61 = @61' */
  /* #815: @26 = mac(@56,@38,@26) */
  casadi_mtimes((&w56), casadi_s20, w38, casadi_s1, w26, casadi_s0, w, 0);
  /* #816: @26 = @26' */
  /* #817: @61 = (@61+@26) */
  for (i=0, rr=w61, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #818: {@56, @54, @44, @53} = vertsplit(@61) */
  w56 = w61[0];
  w54 = w61[1];
  w44 = w61[2];
  w53 = w61[3];
  /* #819: @55 = (-@52) */
  w55 = (- w52 );
  /* #820: @70 = vertcat(@59, @59, @59, @55) */
  rr=(&w70);
  *rr++ = w55;
  /* #821: @70 = (@70/@8) */
  w70 /= w08;
  /* #822: @61 = dense(@70) */
  casadi_densify((&w70), casadi_s21, w61, 0);
  /* #823: @70 = project(@31) */
  casadi_sparsify(w31, (&w70), casadi_s21, 0);
  /* #824: @52 = sparsity_cast(@52) */
  /* #825: @55 = dot(@70, @52) */
  w55 = casadi_dot(1, (&w70), (&w52));
  /* #826: @55 = (@55/@8) */
  w55 /= w08;
  /* #827: @27 = (@27*@55) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) *= w55;
  /* #828: @61 = (@61-@27) */
  for (i=0, rr=w61, cs=w27; i<4; ++i) (*rr++) -= (*cs++);
  /* #829: {@70, @74, @63, @73} = vertsplit(@61) */
  w70 = w61[0];
  w74 = w61[1];
  w63 = w61[2];
  w73 = w61[3];
  /* #830: @18 = (@4*@70) */
  w18  = (w04*w70);
  /* #831: @47 = (@5*@74) */
  w47  = (w05*w74);
  /* #832: @18 = (@18-@47) */
  w18 -= w47;
  /* #833: @47 = (@6*@63) */
  w47  = (w06*w63);
  /* #834: @18 = (@18-@47) */
  w18 -= w47;
  /* #835: @47 = (@7*@73) */
  w47  = (w07*w73);
  /* #836: @18 = (@18-@47) */
  w18 -= w47;
  /* #837: @47 = (@5*@70) */
  w47  = (w05*w70);
  /* #838: @71 = (@4*@74) */
  w71  = (w04*w74);
  /* #839: @47 = (@47+@71) */
  w47 += w71;
  /* #840: @71 = (@7*@63) */
  w71  = (w07*w63);
  /* #841: @47 = (@47+@71) */
  w47 += w71;
  /* #842: @71 = (@6*@73) */
  w71  = (w06*w73);
  /* #843: @47 = (@47-@71) */
  w47 -= w71;
  /* #844: @71 = (@6*@70) */
  w71  = (w06*w70);
  /* #845: @75 = (@7*@74) */
  w75  = (w07*w74);
  /* #846: @71 = (@71-@75) */
  w71 -= w75;
  /* #847: @75 = (@4*@63) */
  w75  = (w04*w63);
  /* #848: @71 = (@71+@75) */
  w71 += w75;
  /* #849: @75 = (@5*@73) */
  w75  = (w05*w73);
  /* #850: @71 = (@71+@75) */
  w71 += w75;
  /* #851: @70 = (@7*@70) */
  w70  = (w07*w70);
  /* #852: @74 = (@6*@74) */
  w74  = (w06*w74);
  /* #853: @70 = (@70+@74) */
  w70 += w74;
  /* #854: @63 = (@5*@63) */
  w63  = (w05*w63);
  /* #855: @70 = (@70-@63) */
  w70 -= w63;
  /* #856: @73 = (@4*@73) */
  w73  = (w04*w73);
  /* #857: @70 = (@70+@73) */
  w70 += w73;
  /* #858: @27 = vertcat(@18, @47, @71, @70) */
  rr=w27;
  *rr++ = w18;
  *rr++ = w47;
  *rr++ = w71;
  *rr++ = w70;
  /* #859: @26 = (-@27) */
  for (i=0, rr=w26, cs=w27; i<4; ++i) *rr++ = (- *cs++ );
  /* #860: @26 = (@13?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #861: @27 = (@12?@27:0) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #862: @26 = (@26+@27) */
  for (i=0, rr=w26, cs=w27; i<4; ++i) (*rr++) += (*cs++);
  /* #863: @81 = @26[1:4] */
  for (rr=w81, cs=w26+1; cs!=w26+4; cs+=1) *rr++ = *cs;
  /* #864: @18 = dot(@20, @81) */
  w18 = casadi_dot(3, w20, w81);
  /* #865: @18 = (@18/@14) */
  w18 /= w14;
  /* #866: @47 = (@18/@10) */
  w47  = (w18/w10);
  /* #867: @17 = (@17*@18) */
  w17 *= w18;
  /* #868: @71 = @26[0] */
  for (rr=(&w71), cs=w26+0; cs!=w26+1; cs+=1) *rr++ = *cs;
  /* #869: @15 = (@15*@71) */
  w15 *= w71;
  /* #870: @17 = (@17+@15) */
  w17 += w15;
  /* #871: @62 = (@62*@17) */
  w62 *= w17;
  /* #872: @47 = (@47-@62) */
  w47 -= w62;
  /* #873: @47 = (@0*@47) */
  w47  = (w00*w47);
  /* #874: @66 = (2.*@81) */
  for (i=0, rr=w66, cs=w81; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #875: @41 = (@9*@66) */
  for (i=0, rr=w41, cs=w66; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #876: @62 = (@16*@18) */
  w62  = (w16*w18);
  /* #877: @15 = (@11*@71) */
  w15  = (w11*w71);
  /* #878: @62 = (@62-@15) */
  w62 -= w15;
  /* #879: @25 = (@34*@62) */
  for (i=0, rr=w25, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #880: @41 = (@41+@25) */
  for (i=0, rr=w41, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #881: @41 = (@41/@3) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w03;
  /* #882: @35 = (@35*@18) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) *= w18;
  /* #883: @41 = (@41-@35) */
  for (i=0, rr=w41, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #884: @35 = @41' */
  casadi_copy(w41, 3, w35);
  /* #885: @25 = mac(@35,@23,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #886: @25 = @25' */
  /* #887: @1 = mac(@35,@39,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #888: @1 = @1' */
  /* #889: @25 = (@25+@1) */
  for (i=0, rr=w25, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #890: @1 = (@25/@3) */
  for (i=0, rr=w01, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #891: @42 = (@42*@18) */
  for (i=0, rr=w42; i<3; ++i) (*rr++) *= w18;
  /* #892: @1 = (@1-@42) */
  for (i=0, rr=w01, cs=w42; i<3; ++i) (*rr++) -= (*cs++);
  /* #893: @15 = dot(@34, @1) */
  w15 = casadi_dot(3, w34, w01);
  /* #894: @70 = dot(@66, @40) */
  w70 = casadi_dot(3, w66, w40);
  /* #895: @15 = (@15+@70) */
  w15 += w70;
  /* #896: @11 = (@11*@15) */
  w11 *= w15;
  /* #897: @47 = (@47+@11) */
  w47 += w11;
  /* #898: @47 = (-@47) */
  w47 = (- w47 );
  /* #899: (@33[0] += @47) */
  for (rr=w33+0, cs=(&w47); rr!=w33+1; rr+=1) *rr += *cs++;
  /* #900: @47 = dot(@36, @25) */
  w47 = casadi_dot(3, w36, w25);
  /* #901: @41 = (@41/@3) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w03;
  /* #902: @65 = (@65*@18) */
  for (i=0, rr=w65; i<3; ++i) (*rr++) *= w18;
  /* #903: @41 = (@41-@65) */
  for (i=0, rr=w41, cs=w65; i<3; ++i) (*rr++) -= (*cs++);
  /* #904: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (- *cs++ );
  /* #905: @3 = dot(@41, @37) */
  w03 = casadi_dot(3, w41, w37);
  /* #906: @47 = (@47+@3) */
  w47 += w03;
  /* #907: @71 = (@71/@10) */
  w71 /= w10;
  /* #908: @68 = (@68*@17) */
  w68 *= w17;
  /* #909: @71 = (@71-@68) */
  w71 -= w68;
  /* #910: @0 = (@0*@71) */
  w00 *= w71;
  /* #911: @16 = (@16*@15) */
  w16 *= w15;
  /* #912: @0 = (@0+@16) */
  w00 += w16;
  /* #913: @47 = (@47+@0) */
  w47 += w00;
  /* #914: @47 = (@47/@14) */
  w47 /= w14;
  /* #915: @43 = (@43*@18) */
  w43 *= w18;
  /* #916: @47 = (@47-@43) */
  w47 -= w43;
  /* #917: @20 = (@20*@47) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w47;
  /* #918: @81 = (@2*@81) */
  for (i=0, rr=w81, cs=w81; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #919: @20 = (@20+@81) */
  for (i=0, rr=w20, cs=w81; i<3; ++i) (*rr++) += (*cs++);
  /* #920: @40 = (@40*@62) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) *= w62;
  /* #921: @1 = (@9*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #922: @40 = (@40+@1) */
  for (i=0, rr=w40, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #923: @40 = (2.*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #924: @20 = (@20+@40) */
  for (i=0, rr=w20, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #925: (@33[1:4] += @20) */
  for (rr=w33+1, cs=w20; rr!=w33+4; rr+=1) *rr += *cs++;
  /* #926: @26 = (@12?@33:0) */
  for (i=0, rr=w26, cs=w33; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #927: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) *rr++ = (- *cs++ );
  /* #928: @33 = (@13?@33:0) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #929: @26 = (@26+@33) */
  for (i=0, rr=w26, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #930: {@13, @12, @9, @62} = vertsplit(@26) */
  w13 = w26[0];
  w12 = w26[1];
  w09 = w26[2];
  w62 = w26[3];
  /* #931: @2 = (@7*@62) */
  w02  = (w07*w62);
  /* #932: @47 = (@6*@9) */
  w47  = (w06*w09);
  /* #933: @2 = (@2+@47) */
  w02 += w47;
  /* #934: @47 = (@5*@12) */
  w47  = (w05*w12);
  /* #935: @2 = (@2+@47) */
  w02 += w47;
  /* #936: @47 = (@4*@13) */
  w47  = (w04*w13);
  /* #937: @2 = (@2+@47) */
  w02 += w47;
  /* #938: @47 = (@6*@62) */
  w47  = (w06*w62);
  /* #939: @43 = (@7*@9) */
  w43  = (w07*w09);
  /* #940: @47 = (@47-@43) */
  w47 -= w43;
  /* #941: @43 = (@4*@12) */
  w43  = (w04*w12);
  /* #942: @47 = (@47+@43) */
  w47 += w43;
  /* #943: @43 = (@5*@13) */
  w43  = (w05*w13);
  /* #944: @47 = (@47-@43) */
  w47 -= w43;
  /* #945: @43 = (@4*@9) */
  w43  = (w04*w09);
  /* #946: @18 = (@5*@62) */
  w18  = (w05*w62);
  /* #947: @43 = (@43-@18) */
  w43 -= w18;
  /* #948: @18 = (@7*@12) */
  w18  = (w07*w12);
  /* #949: @43 = (@43+@18) */
  w43 += w18;
  /* #950: @18 = (@6*@13) */
  w18  = (w06*w13);
  /* #951: @43 = (@43-@18) */
  w43 -= w18;
  /* #952: @4 = (@4*@62) */
  w04 *= w62;
  /* #953: @5 = (@5*@9) */
  w05 *= w09;
  /* #954: @4 = (@4+@5) */
  w04 += w05;
  /* #955: @6 = (@6*@12) */
  w06 *= w12;
  /* #956: @4 = (@4-@6) */
  w04 -= w06;
  /* #957: @7 = (@7*@13) */
  w07 *= w13;
  /* #958: @4 = (@4-@7) */
  w04 -= w07;
  /* #959: @26 = vertcat(@2, @47, @43, @4) */
  rr=w26;
  *rr++ = w02;
  *rr++ = w47;
  *rr++ = w43;
  *rr++ = w04;
  /* #960: @2 = dot(@30, @26) */
  w02 = casadi_dot(4, w30, w26);
  /* #961: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #962: @64 = (@64*@55) */
  for (i=0, rr=w64; i<4; ++i) (*rr++) *= w55;
  /* #963: @61 = (@61-@64) */
  for (i=0, rr=w61, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #964: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #965: @47 = dot(@61, @32) */
  w47 = casadi_dot(4, w61, w32);
  /* #966: @2 = (@2+@47) */
  w02 += w47;
  /* #967: @2 = (@2/@8) */
  w02 /= w08;
  /* #968: @69 = (@69*@55) */
  w69 *= w55;
  /* #969: @2 = (@2-@69) */
  w02 -= w69;
  /* #970: @31 = (@31*@2) */
  for (i=0, rr=w31; i<4; ++i) (*rr++) *= w02;
  /* #971: @45 = (@45*@52) */
  w45 *= w52;
  /* #972: @61 = dense(@45) */
  casadi_densify((&w45), casadi_s21, w61, 0);
  /* #973: @31 = (@31+@61) */
  for (i=0, rr=w31, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #974: (@21[6:10] += @31) */
  for (rr=w21+6, cs=w31; rr!=w21+10; rr+=1) *rr += *cs++;
  /* #975: {@45, @52, @2, @69, @47, @43, @4, @7, @13, @6, @12, @5, @9} = vertsplit(@21) */
  w45 = w21[0];
  w52 = w21[1];
  w02 = w21[2];
  w69 = w21[3];
  w47 = w21[4];
  w43 = w21[5];
  w04 = w21[6];
  w07 = w21[7];
  w13 = w21[8];
  w06 = w21[9];
  w12 = w21[10];
  w05 = w21[11];
  w09 = w21[12];
  /* #976: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #977: @28 = (@28*@55) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) *= w55;
  /* #978: @26 = (@26-@28) */
  for (i=0, rr=w26, cs=w28; i<4; ++i) (*rr++) -= (*cs++);
  /* #979: {@55, @8, @62, @18} = vertsplit(@26) */
  w55 = w26[0];
  w08 = w26[1];
  w62 = w26[2];
  w18 = w26[3];
  /* #980: @55 = (@55+@4) */
  w55 += w04;
  /* #981: @7 = (@7-@8) */
  w07 -= w08;
  /* #982: @13 = (@13-@62) */
  w13 -= w62;
  /* #983: @6 = (@6-@18) */
  w06 -= w18;
  /* #984: @19 = vertcat(@56, @54, @44, @53, @45, @52, @2, @69, @47, @43, @55, @7, @13, @6, @12, @5, @9) */
  rr=w19;
  *rr++ = w56;
  *rr++ = w54;
  *rr++ = w44;
  *rr++ = w53;
  *rr++ = w45;
  *rr++ = w52;
  *rr++ = w02;
  *rr++ = w69;
  *rr++ = w47;
  *rr++ = w43;
  *rr++ = w55;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w05;
  *rr++ = w09;
  /* #985: @83 = @19[:20:10;:4] */
  for (rr=w83, cs=w19+0; cs!=w19+20; cs+=10) for (ct=cs+0; ct!=cs+4; ct+=1) *rr++ = *ct;
  /* #986: (@57[:50:25;12:16] = @83) */
  for (rr=w57+0, cs=w83; rr!=w57+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *cs++;
  /* #987: (@57[:50:25;3:19:4] = @83) */
  for (rr=w57+0, cs=w83; rr!=w57+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *cs++;
  /* #988: @84 = @57' */
  casadi_trans(w57,casadi_s22, w84, casadi_s22, iw);
  /* #989: output[2][0] = @84 */
  casadi_copy(w84, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s23;
    case 1: return casadi_s24;
    case 2: return casadi_s25;
    case 3: return casadi_s26;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s27;
    case 1: return casadi_s26;
    case 2: return casadi_s22;
    case 3: return casadi_s28;
    case 4: return casadi_s29;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 356;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 22*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 18*sizeof(casadi_int);
  if (sz_w) *sz_w = 356*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
