/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = 
  {3, 3, 0, 3, 5, 6, 0, 1,
  2, 1, 2, 2};
static const casadi_int casadi_s3[12] = 
  {3, 3, 0, 1, 3, 6, 0, 0,
  1, 0, 1, 2};
static const casadi_int casadi_s4[3] = {14, 1, 1};
static const casadi_int casadi_s5[3] = {5, 1, 1};
static const casadi_int casadi_s6[3] = {0, 1, 1};
static const casadi_int casadi_s7[19] = 
  {19, 1, 0, 15, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 14, 15,
  16, 17, 18};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

static const casadi_real casadi_zeros[14] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* Drone_ode_complete_expl_vde_adj:(i0[14],i1[14],i2[5],i3[0])->(o0[19x1,15nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w01, w02, w03, *w05=w+23, *w06=w+27, w07, w08, w09, w10, w11, w12;
  casadi_real w13, *w14=w+37, w15, w16, w17, *w18=w+49, w19, *w20=w+54, w21, w22, *w23=w+60, w24;
  casadi_real *w25=w+70, *w26=w+73, *w27=w+82, *w28=w+91, *w29=w+100, *w30=w+109, *w31=w+118, w32, w33, *w34=w+124, *w35=w+127, *w36=w+130;
  casadi_real w37, w38;
  const casadi_real *cr, *cs, *ct, *ss, *wr00, *wr04, *wr05, *wr06, *wr26;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: {@1, @2, @3, @4, @5, @6, @7} = vertsplit(@0) */
  w01 = wr00[0];
  w02 = wr00[1];
  w03 = wr00[2];
  wr04 = wr00+3;
  wr05 = wr00+6;
  wr06 = wr00+10;
  w07 = wr00[13];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #5: @3 = input[0][12] */
  w03 = arg[0] ? arg[0][12] : 0;
  /* #6: @2 = 0.5 */
  w02 = 5.0000000000000000e-01;
  /* #7: @5 = (@2*@5) */
  for (i=0, rr=w05, cs=wr05; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #8: {@2, @1, @8, @9} = vertsplit(@5) */
  w02 = w05[0];
  w01 = w05[1];
  w08 = w05[2];
  w09 = w05[3];
  /* #9: @10 = (@3*@9) */
  w10  = (w03*w09);
  /* #10: @11 = input[0][11] */
  w11 = arg[0] ? arg[0][11] : 0;
  /* #11: @12 = (@11*@8) */
  w12  = (w11*w08);
  /* #12: @10 = (@10+@12) */
  w10 += w12;
  /* #13: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #14: @13 = (@12*@1) */
  w13  = (w12*w01);
  /* #15: @10 = (@10+@13) */
  w10 += w13;
  /* #16: @5 = zeros(4x1) */
  casadi_clear(w05, 4);
  /* #17: @14 = zeros(3x3) */
  casadi_clear(w14, 9);
  /* #18: @13 = input[0][6] */
  w13 = arg[0] ? arg[0][6] : 0;
  /* #19: @15 = input[0][7] */
  w15 = arg[0] ? arg[0][7] : 0;
  /* #20: @16 = input[0][8] */
  w16 = arg[0] ? arg[0][8] : 0;
  /* #21: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #22: @18 = vertcat(@13, @15, @16, @17) */
  rr=w18;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #23: @19 = ||@18||_F */
  w19 = casadi_norm_2(4, w18);
  /* #24: @20 = (@18/@19) */
  for (i=0, rr=w20, cr=w18; i<4; ++i) (*rr++)  = ((*cr++)/w19);
  /* #25: @21 = @20[3] */
  for (rr=(&w21), cs=w20+3; cs!=w20+4; cs+=1) *rr++ = *cs;
  /* #26: @22 = (-@21) */
  w22 = (- w21 );
  /* #27: @23 = @14; (@23[3] = @22) */
  casadi_copy(w14, 9, w23);
  for (rr=w23+3, cs=(&w22); rr!=w23+4; rr+=1) *rr = *cs++;
  /* #28: @22 = @20[2] */
  for (rr=(&w22), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #29: (@23[6] = @22) */
  for (rr=w23+6, cs=(&w22); rr!=w23+7; rr+=1) *rr = *cs++;
  /* #30: (@23[1] = @21) */
  for (rr=w23+1, cs=(&w21); rr!=w23+2; rr+=1) *rr = *cs++;
  /* #31: @21 = @20[1] */
  for (rr=(&w21), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #32: @24 = (-@21) */
  w24 = (- w21 );
  /* #33: (@23[7] = @24) */
  for (rr=w23+7, cs=(&w24); rr!=w23+8; rr+=1) *rr = *cs++;
  /* #34: @22 = (-@22) */
  w22 = (- w22 );
  /* #35: (@23[2] = @22) */
  for (rr=w23+2, cs=(&w22); rr!=w23+3; rr+=1) *rr = *cs++;
  /* #36: (@23[5] = @21) */
  for (rr=w23+5, cs=(&w21); rr!=w23+6; rr+=1) *rr = *cs++;
  /* #37: @21 = 0 */
  w21 = 0.;
  /* #38: @22 = input[2][0] */
  w22 = arg[2] ? arg[2][0] : 0;
  /* #39: @25 = vertcat(@21, @21, @22) */
  rr=w25;
  *rr++ = w21;
  *rr++ = w21;
  *rr++ = w22;
  /* #40: @25 = @25' */
  /* #41: @26 = mac(@4,@25,@14) */
  casadi_copy(w14, 9, w26);
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr04+j, ct=w25+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #42: @22 = dot(@23, @26) */
  w22 = casadi_dot(9, w23, w26);
  /* #43: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #44: (@5[0] += @22) */
  for (rr=w05+0, cs=(&w22); rr!=w05+1; rr+=1) *rr += *cs++;
  /* #45: @22 = @20[0] */
  for (rr=(&w22), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #46: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #47: @27 = (@22*@26) */
  for (i=0, rr=w27, cs=w26; i<9; ++i) (*rr++)  = (w22*(*cs++));
  /* #48: @28 = (2.*@23) */
  for (i=0, rr=w28, cs=w23; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #49: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #50: @30 = mac(@29,@26,@14) */
  casadi_copy(w14, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #51: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<9; ++i) (*rr++) += (*cs++);
  /* #52: @30 = @23' */
  for (i=0, rr=w30, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #53: @29 = mac(@26,@30,@14) */
  casadi_copy(w14, 9, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #54: @29 = (2.*@29) */
  for (i=0, rr=w29, cs=w29; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #55: @27 = (@27+@29) */
  for (i=0, rr=w27, cs=w29; i<9; ++i) (*rr++) += (*cs++);
  /* #56: @24 = @27[5] */
  for (rr=(&w24), cs=w27+5; cs!=w27+6; cs+=1) *rr++ = *cs;
  /* #57: (@5[1] += @24) */
  for (rr=w05+1, cs=(&w24); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #58: (@27[5] = @21) */
  for (rr=w27+5, cs=(&w21); rr!=w27+6; rr+=1) *rr = *cs++;
  /* #59: @24 = @27[2] */
  for (rr=(&w24), cs=w27+2; cs!=w27+3; cs+=1) *rr++ = *cs;
  /* #60: @24 = (-@24) */
  w24 = (- w24 );
  /* #61: (@5[2] += @24) */
  for (rr=w05+2, cs=(&w24); rr!=w05+3; rr+=1) *rr += *cs++;
  /* #62: (@27[2] = @21) */
  for (rr=w27+2, cs=(&w21); rr!=w27+3; rr+=1) *rr = *cs++;
  /* #63: @24 = @27[7] */
  for (rr=(&w24), cs=w27+7; cs!=w27+8; cs+=1) *rr++ = *cs;
  /* #64: @24 = (-@24) */
  w24 = (- w24 );
  /* #65: (@5[1] += @24) */
  for (rr=w05+1, cs=(&w24); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #66: (@27[7] = @21) */
  for (rr=w27+7, cs=(&w21); rr!=w27+8; rr+=1) *rr = *cs++;
  /* #67: @24 = @27[1] */
  for (rr=(&w24), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #68: (@5[3] += @24) */
  for (rr=w05+3, cs=(&w24); rr!=w05+4; rr+=1) *rr += *cs++;
  /* #69: (@27[1] = @21) */
  for (rr=w27+1, cs=(&w21); rr!=w27+2; rr+=1) *rr = *cs++;
  /* #70: @24 = @27[6] */
  for (rr=(&w24), cs=w27+6; cs!=w27+7; cs+=1) *rr++ = *cs;
  /* #71: (@5[2] += @24) */
  for (rr=w05+2, cs=(&w24); rr!=w05+3; rr+=1) *rr += *cs++;
  /* #72: (@27[6] = @21) */
  for (rr=w27+6, cs=(&w21); rr!=w27+7; rr+=1) *rr = *cs++;
  /* #73: @24 = @27[3] */
  for (rr=(&w24), cs=w27+3; cs!=w27+4; cs+=1) *rr++ = *cs;
  /* #74: @24 = (-@24) */
  w24 = (- w24 );
  /* #75: (@5[3] += @24) */
  for (rr=w05+3, cs=(&w24); rr!=w05+4; rr+=1) *rr += *cs++;
  /* #76: @31 = (@5/@19) */
  for (i=0, rr=w31, cr=w05; i<4; ++i) (*rr++)  = ((*cr++)/w19);
  /* #77: @20 = (@20/@19) */
  for (i=0, rr=w20; i<4; ++i) (*rr++) /= w19;
  /* #78: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #79: @24 = dot(@20, @5) */
  w24 = casadi_dot(4, w20, w05);
  /* #80: @24 = (@24/@19) */
  w24 /= w19;
  /* #81: @18 = (@24*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w24*(*cs++));
  /* #82: @31 = (@31+@18) */
  for (i=0, rr=w31, cs=w18; i<4; ++i) (*rr++) += (*cs++);
  /* #83: {@24, @19, @32, @33} = vertsplit(@31) */
  w24 = w31[0];
  w19 = w31[1];
  w32 = w31[2];
  w33 = w31[3];
  /* #84: @10 = (@10+@24) */
  w10 += w24;
  /* #85: output[0][3] = @10 */
  if (res[0]) res[0][3] = w10;
  /* #86: @10 = (@11*@9) */
  w10  = (w11*w09);
  /* #87: @24 = (@3*@8) */
  w24  = (w03*w08);
  /* #88: @10 = (@10-@24) */
  w10 -= w24;
  /* #89: @24 = (@12*@2) */
  w24  = (w12*w02);
  /* #90: @10 = (@10-@24) */
  w10 -= w24;
  /* #91: @10 = (@10+@19) */
  w10 += w19;
  /* #92: output[0][4] = @10 */
  if (res[0]) res[0][4] = w10;
  /* #93: @10 = (@3*@1) */
  w10  = (w03*w01);
  /* #94: @19 = (@12*@9) */
  w19  = (w12*w09);
  /* #95: @10 = (@10-@19) */
  w10 -= w19;
  /* #96: @19 = (@11*@2) */
  w19  = (w11*w02);
  /* #97: @10 = (@10-@19) */
  w10 -= w19;
  /* #98: @10 = (@10+@32) */
  w10 += w32;
  /* #99: output[0][5] = @10 */
  if (res[0]) res[0][5] = w10;
  /* #100: @10 = (@12*@8) */
  w10  = (w12*w08);
  /* #101: @32 = (@11*@1) */
  w32  = (w11*w01);
  /* #102: @10 = (@10-@32) */
  w10 -= w32;
  /* #103: @32 = (@3*@2) */
  w32  = (w03*w02);
  /* #104: @10 = (@10-@32) */
  w10 -= w32;
  /* #105: @10 = (@10+@33) */
  w10 += w33;
  /* #106: output[0][6] = @10 */
  if (res[0]) res[0][6] = w10;
  /* #107: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #108: @10 = 0.00305587 */
  w10 = 3.0558700000000000e-03;
  /* #109: @34 = horzcat(@10, @21, @21) */
  rr=w34;
  *rr++ = w10;
  *rr++ = w21;
  *rr++ = w21;
  /* #110: @34 = @34' */
  /* #111: @10 = 0.00159695 */
  w10 = 1.5969500000000000e-03;
  /* #112: @35 = horzcat(@21, @10, @21) */
  rr=w35;
  *rr++ = w21;
  *rr++ = w10;
  *rr++ = w21;
  /* #113: @35 = @35' */
  /* #114: @10 = 0.00159687 */
  w10 = 1.5968700000000000e-03;
  /* #115: @36 = horzcat(@21, @21, @10) */
  rr=w36;
  *rr++ = w21;
  *rr++ = w21;
  *rr++ = w10;
  /* #116: @36 = @36' */
  /* #117: @27 = horzcat(@34, @35, @36) */
  rr=w27;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<3; ++i) *rr++ = *cs++;
  /* #118: @29 = @27' */
  for (i=0, rr=w29, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #119: @34 = vertcat(@12, @11, @3) */
  rr=w34;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w03;
  /* #120: @35 = mac(@29,@34,@25) */
  casadi_copy(w25, 3, w35);
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #121: @21 = @35[1] */
  for (rr=(&w21), cs=w35+1; cs!=w35+2; cs+=1) *rr++ = *cs;
  /* #122: @26 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr26 = casadi_c0;
  /* #123: @30 = (@29\@26) */
  rr = w30;
  ss = w29;
  casadi_copy(wr26, 9, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #124: @29 = @30' */
  for (i=0, rr=w29, cs=w30; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #125: @34 = mac(@29,@6,@25) */
  casadi_copy(w25, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=wr06+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #126: @6 = (-@34) */
  for (i=0, rr=w06, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #127: {@10, @33, @32} = vertsplit(@6) */
  w10 = w06[0];
  w33 = w06[1];
  w32 = w06[2];
  /* #128: @19 = (@21*@32) */
  w19  = (w21*w32);
  /* #129: @24 = @35[2] */
  for (rr=(&w24), cs=w35+2; cs!=w35+3; cs+=1) *rr++ = *cs;
  /* #130: @37 = (@24*@33) */
  w37  = (w24*w33);
  /* #131: @19 = (@19-@37) */
  w19 -= w37;
  /* #132: @37 = (@3*@33) */
  w37  = (w03*w33);
  /* #133: @38 = (@11*@32) */
  w38  = (w11*w32);
  /* #134: @37 = (@37-@38) */
  w37 -= w38;
  /* #135: @6 = @25; (@6[0] += @37) */
  casadi_copy(w25, 3, w06);
  for (rr=w06+0, cs=(&w37); rr!=w06+1; rr+=1) *rr += *cs++;
  /* #136: @37 = (@12*@32) */
  w37  = (w12*w32);
  /* #137: @3 = (@3*@10) */
  w03 *= w10;
  /* #138: @37 = (@37-@3) */
  w37 -= w03;
  /* #139: (@6[1] += @37) */
  for (rr=w06+1, cs=(&w37); rr!=w06+2; rr+=1) *rr += *cs++;
  /* #140: @11 = (@11*@10) */
  w11 *= w10;
  /* #141: @12 = (@12*@33) */
  w12 *= w33;
  /* #142: @11 = (@11-@12) */
  w11 -= w12;
  /* #143: (@6[2] += @11) */
  for (rr=w06+2, cs=(&w11); rr!=w06+3; rr+=1) *rr += *cs++;
  /* #144: @36 = mac(@27,@6,@25) */
  casadi_copy(w25, 3, w36);
  for (i=0, rr=w36; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w06+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #145: {@11, @12, @37} = vertsplit(@36) */
  w11 = w36[0];
  w12 = w36[1];
  w37 = w36[2];
  /* #146: @19 = (@19+@11) */
  w19 += w11;
  /* #147: @11 = (@16*@9) */
  w11  = (w16*w09);
  /* #148: @19 = (@19-@11) */
  w19 -= w11;
  /* #149: @11 = (@17*@8) */
  w11  = (w17*w08);
  /* #150: @19 = (@19+@11) */
  w19 += w11;
  /* #151: @11 = (@13*@1) */
  w11  = (w13*w01);
  /* #152: @19 = (@19+@11) */
  w19 += w11;
  /* #153: @11 = (@15*@2) */
  w11  = (w15*w02);
  /* #154: @19 = (@19-@11) */
  w19 -= w11;
  /* #155: output[0][7] = @19 */
  if (res[0]) res[0][7] = w19;
  /* #156: @24 = (@24*@10) */
  w24 *= w10;
  /* #157: @19 = @35[0] */
  for (rr=(&w19), cs=w35+0; cs!=w35+1; cs+=1) *rr++ = *cs;
  /* #158: @32 = (@19*@32) */
  w32  = (w19*w32);
  /* #159: @24 = (@24-@32) */
  w24 -= w32;
  /* #160: @24 = (@24+@12) */
  w24 += w12;
  /* #161: @12 = (@15*@9) */
  w12  = (w15*w09);
  /* #162: @24 = (@24+@12) */
  w24 += w12;
  /* #163: @12 = (@13*@8) */
  w12  = (w13*w08);
  /* #164: @24 = (@24+@12) */
  w24 += w12;
  /* #165: @12 = (@17*@1) */
  w12  = (w17*w01);
  /* #166: @24 = (@24-@12) */
  w24 -= w12;
  /* #167: @12 = (@16*@2) */
  w12  = (w16*w02);
  /* #168: @24 = (@24-@12) */
  w24 -= w12;
  /* #169: output[0][8] = @24 */
  if (res[0]) res[0][8] = w24;
  /* #170: @19 = (@19*@33) */
  w19 *= w33;
  /* #171: @21 = (@21*@10) */
  w21 *= w10;
  /* #172: @19 = (@19-@21) */
  w19 -= w21;
  /* #173: @19 = (@19+@37) */
  w19 += w37;
  /* #174: @13 = (@13*@9) */
  w13 *= w09;
  /* #175: @19 = (@19+@13) */
  w19 += w13;
  /* #176: @15 = (@15*@8) */
  w15 *= w08;
  /* #177: @19 = (@19-@15) */
  w19 -= w15;
  /* #178: @16 = (@16*@1) */
  w16 *= w01;
  /* #179: @19 = (@19+@16) */
  w19 += w16;
  /* #180: @17 = (@17*@2) */
  w17 *= w02;
  /* #181: @19 = (@19-@17) */
  w19 -= w17;
  /* #182: output[0][9] = @19 */
  if (res[0]) res[0][9] = w19;
  /* #183: @14 = mac(@28,@23,@14) */
  for (i=0, rr=w14; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #184: @26 = (@26+@14) */
  for (i=0, rr=w26, cr=wr26, cs=w14; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #185: @23 = (@22*@23) */
  for (i=0, rr=w23, cs=w23; i<9; ++i) (*rr++)  = (w22*(*cs++));
  /* #186: @26 = (@26+@23) */
  for (i=0, rr=w26, cs=w23; i<9; ++i) (*rr++) += (*cs++);
  /* #187: @23 = @26' */
  for (i=0, rr=w23, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #188: @25 = mac(@23,@4,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w23+j, ct=wr04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #189: {NULL, NULL, @22} = vertsplit(@25) */
  w22 = w25[2];
  /* #190: output[0][10] = @22 */
  if (res[0]) res[0][10] = w22;
  /* #191: {@22, @19, @17} = vertsplit(@34) */
  w22 = w34[0];
  w19 = w34[1];
  w17 = w34[2];
  /* #192: output[0][11] = @22 */
  if (res[0]) res[0][11] = w22;
  /* #193: output[0][12] = @19 */
  if (res[0]) res[0][12] = w19;
  /* #194: output[0][13] = @17 */
  if (res[0]) res[0][13] = w17;
  /* #195: output[0][14] = @7 */
  if (res[0]) res[0][14] = w07;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 135;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 135*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
