/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = 
  {3, 3, 0, 3, 5, 6, 0, 1,
  2, 1, 2, 2};
static const casadi_int casadi_s3[12] = 
  {3, 3, 0, 1, 3, 6, 0, 0,
  1, 0, 1, 2};
static const casadi_int casadi_s4[3] = {14, 1, 1};
static const casadi_int casadi_s5[3] = {5, 1, 1};
static const casadi_int casadi_s6[3] = {7, 1, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c1[3] = {0., 0., 1.};

/* Drone_ode_complete_expl_ode_fun:(i0[14],i1[5],i2[7])->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, *w02=w+7, *w03=w+16, w04, w05, w06, *w07=w+28, w08, w09, *w10=w+34;
  casadi_real w11, w12, *w13=w+45, *w14=w+54, *w15=w+57, w16, w17, w18, w19, w20, *w21=w+65;
  const casadi_real *cr, *cs, *ct, *ss, *wr02;
  /* #0: @0 = input[0][3] */
  w00 = arg[0] ? arg[0][3] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @0 = input[0][4] */
  w00 = arg[0] ? arg[0][4] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #4: @0 = input[0][5] */
  w00 = arg[0] ? arg[0][5] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  /* #6: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #7: @2 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr02 = casadi_c0;
  /* #8: @3 = zeros(3x3) */
  casadi_clear(w03, 9);
  /* #9: @0 = input[0][6] */
  w00 = arg[0] ? arg[0][6] : 0;
  /* #10: @4 = input[0][7] */
  w04 = arg[0] ? arg[0][7] : 0;
  /* #11: @5 = input[0][8] */
  w05 = arg[0] ? arg[0][8] : 0;
  /* #12: @6 = input[0][9] */
  w06 = arg[0] ? arg[0][9] : 0;
  /* #13: @7 = vertcat(@0, @4, @5, @6) */
  rr=w07;
  *rr++ = w00;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  /* #14: @8 = ||@7||_F */
  w08 = casadi_norm_2(4, w07);
  /* #15: @7 = (@7/@8) */
  for (i=0, rr=w07; i<4; ++i) (*rr++) /= w08;
  /* #16: @8 = @7[3] */
  for (rr=(&w08), cs=w07+3; cs!=w07+4; cs+=1) *rr++ = *cs;
  /* #17: @9 = (-@8) */
  w09 = (- w08 );
  /* #18: @10 = @3; (@10[3] = @9) */
  casadi_copy(w03, 9, w10);
  for (rr=w10+3, cs=(&w09); rr!=w10+4; rr+=1) *rr = *cs++;
  /* #19: @9 = @7[2] */
  for (rr=(&w09), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #20: (@10[6] = @9) */
  for (rr=w10+6, cs=(&w09); rr!=w10+7; rr+=1) *rr = *cs++;
  /* #21: @11 = @7[1] */
  for (rr=(&w11), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #22: @12 = (-@11) */
  w12 = (- w11 );
  /* #23: (@10[7] = @12) */
  for (rr=w10+7, cs=(&w12); rr!=w10+8; rr+=1) *rr = *cs++;
  /* #24: (@10[1] = @8) */
  for (rr=w10+1, cs=(&w08); rr!=w10+2; rr+=1) *rr = *cs++;
  /* #25: @9 = (-@9) */
  w09 = (- w09 );
  /* #26: (@10[2] = @9) */
  for (rr=w10+2, cs=(&w09); rr!=w10+3; rr+=1) *rr = *cs++;
  /* #27: (@10[5] = @11) */
  for (rr=w10+5, cs=(&w11); rr!=w10+6; rr+=1) *rr = *cs++;
  /* #28: @13 = (2.*@10) */
  for (i=0, rr=w13, cs=w10; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #29: @3 = mac(@13,@10,@3) */
  for (i=0, rr=w03; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w13+j, ct=w10+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #30: @3 = (@2+@3) */
  for (i=0, rr=w03, cr=wr02, cs=w03; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #31: @11 = @7[0] */
  for (rr=(&w11), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #32: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #33: @10 = (@11*@10) */
  for (i=0, rr=w10, cs=w10; i<9; ++i) (*rr++)  = (w11*(*cs++));
  /* #34: @3 = (@3+@10) */
  for (i=0, rr=w03, cs=w10; i<9; ++i) (*rr++) += (*cs++);
  /* #35: @11 = 0 */
  w11 = 0.;
  /* #36: @9 = input[1][0] */
  w09 = arg[1] ? arg[1][0] : 0;
  /* #37: @14 = vertcat(@11, @11, @9) */
  rr=w14;
  *rr++ = w11;
  *rr++ = w11;
  *rr++ = w09;
  /* #38: @15 = mac(@3,@14,@1) */
  casadi_copy(w01, 3, w15);
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w03+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #39: @14 = [0, 0, 1] */
  casadi_copy(casadi_c1, 3, w14);
  /* #40: @9 = 9.81 */
  w09 = 9.8100000000000005e+00;
  /* #41: @14 = (@14*@9) */
  for (i=0, rr=w14; i<3; ++i) (*rr++) *= w09;
  /* #42: @15 = (@15-@14) */
  for (i=0, rr=w15, cs=w14; i<3; ++i) (*rr++) -= (*cs++);
  /* #43: output[0][3] = @15 */
  if (res[0]) casadi_copy(w15, 3, res[0]+3);
  /* #44: @9 = 0.5 */
  w09 = 5.0000000000000000e-01;
  /* #45: @8 = input[0][10] */
  w08 = arg[0] ? arg[0][10] : 0;
  /* #46: @12 = (@4*@8) */
  w12  = (w04*w08);
  /* #47: @12 = (-@12) */
  w12 = (- w12 );
  /* #48: @16 = input[0][11] */
  w16 = arg[0] ? arg[0][11] : 0;
  /* #49: @17 = (@5*@16) */
  w17  = (w05*w16);
  /* #50: @12 = (@12-@17) */
  w12 -= w17;
  /* #51: @17 = input[0][12] */
  w17 = arg[0] ? arg[0][12] : 0;
  /* #52: @18 = (@6*@17) */
  w18  = (w06*w17);
  /* #53: @12 = (@12-@18) */
  w12 -= w18;
  /* #54: @18 = (@0*@8) */
  w18  = (w00*w08);
  /* #55: @19 = (@5*@17) */
  w19  = (w05*w17);
  /* #56: @18 = (@18+@19) */
  w18 += w19;
  /* #57: @19 = (@6*@16) */
  w19  = (w06*w16);
  /* #58: @18 = (@18-@19) */
  w18 -= w19;
  /* #59: @19 = (@0*@16) */
  w19  = (w00*w16);
  /* #60: @20 = (@4*@17) */
  w20  = (w04*w17);
  /* #61: @19 = (@19-@20) */
  w19 -= w20;
  /* #62: @6 = (@6*@8) */
  w06 *= w08;
  /* #63: @19 = (@19+@6) */
  w19 += w06;
  /* #64: @0 = (@0*@17) */
  w00 *= w17;
  /* #65: @4 = (@4*@16) */
  w04 *= w16;
  /* #66: @0 = (@0+@4) */
  w00 += w04;
  /* #67: @5 = (@5*@8) */
  w05 *= w08;
  /* #68: @0 = (@0-@5) */
  w00 -= w05;
  /* #69: @7 = vertcat(@12, @18, @19, @0) */
  rr=w07;
  *rr++ = w12;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w00;
  /* #70: @7 = (@9*@7) */
  for (i=0, rr=w07, cs=w07; i<4; ++i) (*rr++)  = (w09*(*cs++));
  /* #71: output[0][4] = @7 */
  if (res[0]) casadi_copy(w07, 4, res[0]+6);
  /* #72: @9 = 0.00305587 */
  w09 = 3.0558700000000000e-03;
  /* #73: @15 = horzcat(@9, @11, @11) */
  rr=w15;
  *rr++ = w09;
  *rr++ = w11;
  *rr++ = w11;
  /* #74: @15 = @15' */
  /* #75: @9 = 0.00159695 */
  w09 = 1.5969500000000000e-03;
  /* #76: @14 = horzcat(@11, @9, @11) */
  rr=w14;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w11;
  /* #77: @14 = @14' */
  /* #78: @9 = 0.00159687 */
  w09 = 1.5968700000000000e-03;
  /* #79: @21 = horzcat(@11, @11, @9) */
  rr=w21;
  *rr++ = w11;
  *rr++ = w11;
  *rr++ = w09;
  /* #80: @21 = @21' */
  /* #81: @3 = horzcat(@15, @14, @21) */
  rr=w03;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #82: @10 = @3' */
  for (i=0, rr=w10, cs=w03; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #83: @2 = (@10\@2) */
  rr = w02;
  ss = w10;
  casadi_copy(wr02, 9, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #84: @11 = input[1][1] */
  w11 = arg[1] ? arg[1][1] : 0;
  /* #85: @9 = input[1][2] */
  w09 = arg[1] ? arg[1][2] : 0;
  /* #86: @12 = input[1][3] */
  w12 = arg[1] ? arg[1][3] : 0;
  /* #87: @15 = vertcat(@11, @9, @12) */
  rr=w15;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w12;
  /* #88: @14 = vertcat(@8, @16, @17) */
  rr=w14;
  *rr++ = w08;
  *rr++ = w16;
  *rr++ = w17;
  /* #89: @21 = mac(@10,@14,@1) */
  casadi_copy(w01, 3, w21);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w10+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #90: @11 = @21[2] */
  for (rr=(&w11), cs=w21+2; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #91: @9 = (@16*@11) */
  w09  = (w16*w11);
  /* #92: @12 = @21[1] */
  for (rr=(&w12), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #93: @18 = (@17*@12) */
  w18  = (w17*w12);
  /* #94: @9 = (@9-@18) */
  w09 -= w18;
  /* #95: @18 = @21[0] */
  for (rr=(&w18), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #96: @17 = (@17*@18) */
  w17 *= w18;
  /* #97: @11 = (@8*@11) */
  w11  = (w08*w11);
  /* #98: @17 = (@17-@11) */
  w17 -= w11;
  /* #99: @8 = (@8*@12) */
  w08 *= w12;
  /* #100: @16 = (@16*@18) */
  w16 *= w18;
  /* #101: @8 = (@8-@16) */
  w08 -= w16;
  /* #102: @21 = vertcat(@9, @17, @8) */
  rr=w21;
  *rr++ = w09;
  *rr++ = w17;
  *rr++ = w08;
  /* #103: @15 = (@15-@21) */
  for (i=0, rr=w15, cs=w21; i<3; ++i) (*rr++) -= (*cs++);
  /* #104: @1 = mac(@2,@15,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w02+j, ct=w15+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #105: output[0][5] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+10);
  /* #106: @9 = input[1][4] */
  w09 = arg[1] ? arg[1][4] : 0;
  /* #107: output[0][6] = @9 */
  if (res[0]) res[0][13] = w09;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 68;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 68*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
